// SPDX-License-Identifier: AGPL-3.0-only
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::isa_types::{BitField, InstrEntry};
mod table;
pub use table::{TABLE, lookup};

/// ENC_MIMG encoding fields (64 bits).
pub mod fields {
    use super::BitField;
    pub const OPM: BitField = BitField { offset: 0, width: 1 };
    pub const NSA: BitField = BitField { offset: 1, width: 2 };
    pub const DIM: BitField = BitField { offset: 3, width: 3 };
    pub const DLC: BitField = BitField { offset: 7, width: 1 };
    pub const DMASK: BitField = BitField { offset: 8, width: 4 };
    pub const UNORM: BitField = BitField { offset: 12, width: 1 };
    pub const GLC: BitField = BitField { offset: 13, width: 1 };
    pub const DA: BitField = BitField { offset: 14, width: 1 };
    pub const R128: BitField = BitField { offset: 15, width: 1 };
    pub const TFE: BitField = BitField { offset: 16, width: 1 };
    pub const LWE: BitField = BitField { offset: 17, width: 1 };
    pub const OP: BitField = BitField { offset: 18, width: 7 };
    pub const SLC: BitField = BitField { offset: 25, width: 1 };
    pub const ENCODING: BitField = BitField { offset: 26, width: 6 };
    pub const VADDR: BitField = BitField { offset: 32, width: 8 };
    pub const VDATA: BitField = BitField { offset: 40, width: 8 };
    pub const SRSRC: BitField = BitField { offset: 48, width: 2 };
    pub const SSAMP: BitField = BitField { offset: 53, width: 2 };
    pub const A16: BitField = BitField { offset: 62, width: 1 };
    pub const D16: BitField = BitField { offset: 63, width: 1 };
}

/// Load a texel from the largest miplevel in an image surface and store the result into a vector register. Perform the f...
pub const IMAGE_LOAD: u16 = 0;
/// Load a texel from a user-specified miplevel in an image surface and store the result into a vector register. Perform ...
pub const IMAGE_LOAD_MIP: u16 = 1;
/// Load a texel from the largest miplevel in an image surface and store the result into a vector register. 8- and 16-bit...
pub const IMAGE_LOAD_PCK: u16 = 2;
/// Load a texel from the largest miplevel in an image surface and store the result into a vector register. 8- and 16-bit...
pub const IMAGE_LOAD_PCK_SGN: u16 = 3;
/// Load a texel from a user-specified miplevel in an image surface and store the result into a vector register. 8- and 1...
pub const IMAGE_LOAD_MIP_PCK: u16 = 4;
/// Load a texel from a user-specified miplevel in an image surface and store the result into a vector register. 8- and 1...
pub const IMAGE_LOAD_MIP_PCK_SGN: u16 = 5;
/// Store a texel from a vector register to the largest miplevel in an image surface. The texel data is converted using t...
pub const IMAGE_STORE: u16 = 8;
/// Store a texel from a vector register to a user-specified miplevel in an image surface. The texel data is converted us...
pub const IMAGE_STORE_MIP: u16 = 9;
/// Store a texel from a vector register to the largest miplevel in an image surface. The texel data is already packed an...
pub const IMAGE_STORE_PCK: u16 = 10;
/// Store a texel from a vector register to a user-specified miplevel in an image surface. The texel data is already pack...
pub const IMAGE_STORE_MIP_PCK: u16 = 11;
/// Gather resource information for a given miplevel provided in the address register. Returns 4 integer values into regi...
pub const IMAGE_GET_RESINFO: u16 = 14;
/// Swap an unsigned 32-bit integer value in the data register with a location in an image surface. Store the original va...
pub const IMAGE_ATOMIC_SWAP: u16 = 15;
/// Compare two unsigned 32-bit integer values stored in the data comparison register and a location in an image surface....
pub const IMAGE_ATOMIC_CMPSWAP: u16 = 16;
/// Add two unsigned 32-bit integer values stored in the data register and a location in an image surface. Store the orig...
pub const IMAGE_ATOMIC_ADD: u16 = 17;
/// Subtract an unsigned 32-bit integer value stored in the data register from a value stored in a location in an image s...
pub const IMAGE_ATOMIC_SUB: u16 = 18;
/// Select the minimum of two signed 32-bit integer inputs, given two values stored in the data register and a location i...
pub const IMAGE_ATOMIC_SMIN: u16 = 20;
/// Select the minimum of two unsigned 32-bit integer inputs, given two values stored in the data register and a location...
pub const IMAGE_ATOMIC_UMIN: u16 = 21;
/// Select the maximum of two signed 32-bit integer inputs, given two values stored in the data register and a location i...
pub const IMAGE_ATOMIC_SMAX: u16 = 22;
/// Select the maximum of two unsigned 32-bit integer inputs, given two values stored in the data register and a location...
pub const IMAGE_ATOMIC_UMAX: u16 = 23;
/// Calculate bitwise AND given two unsigned 32-bit integer values stored in the data register and a location in an image...
pub const IMAGE_ATOMIC_AND: u16 = 24;
/// Calculate bitwise OR given two unsigned 32-bit integer values stored in the data register and a location in an image ...
pub const IMAGE_ATOMIC_OR: u16 = 25;
/// Calculate bitwise XOR given two unsigned 32-bit integer values stored in the data register and a location in an image...
pub const IMAGE_ATOMIC_XOR: u16 = 26;
/// Increment an unsigned 32-bit integer value from a location in an image surface with wraparound to 0 if the value exce...
pub const IMAGE_ATOMIC_INC: u16 = 27;
/// Decrement an unsigned 32-bit integer value from a location in an image surface with wraparound to a value in the data...
pub const IMAGE_ATOMIC_DEC: u16 = 28;
/// Compare two single-precision float values stored in the data comparison register and a location in an image surface. ...
pub const IMAGE_ATOMIC_FCMPSWAP: u16 = 29;
/// Select the minimum of two single-precision float inputs, given two values stored in the data register and a location ...
pub const IMAGE_ATOMIC_FMIN: u16 = 30;
/// Select the maximum of two single-precision float inputs, given two values stored in the data register and a location ...
pub const IMAGE_ATOMIC_FMAX: u16 = 31;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE: u16 = 32;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CL: u16 = 33;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D: u16 = 34;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D_CL: u16 = 35;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_L: u16 = 36;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_B: u16 = 37;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_B_CL: u16 = 38;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_LZ: u16 = 39;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C: u16 = 40;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CL: u16 = 41;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D: u16 = 42;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D_CL: u16 = 43;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_L: u16 = 44;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_B: u16 = 45;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_B_CL: u16 = 46;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_LZ: u16 = 47;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_O: u16 = 48;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CL_O: u16 = 49;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D_O: u16 = 50;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D_CL_O: u16 = 51;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_L_O: u16 = 52;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_B_O: u16 = 53;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_B_CL_O: u16 = 54;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_LZ_O: u16 = 55;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_O: u16 = 56;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CL_O: u16 = 57;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D_O: u16 = 58;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D_CL_O: u16 = 59;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_L_O: u16 = 60;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_B_O: u16 = 61;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_B_CL_O: u16 = 62;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_LZ_O: u16 = 63;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4: u16 = 64;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_CL: u16 = 65;
/// Load 2 horizontal elements from the largest miplevel in an image surface and store the result into a vector register....
pub const IMAGE_LOAD_BY2: u16 = 66;
/// Load 4 horizontal elements from the largest miplevel in an image surface and store the result into a vector register....
pub const IMAGE_LOAD_BY4: u16 = 67;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_L: u16 = 68;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_B: u16 = 69;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_B_CL: u16 = 70;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_LZ: u16 = 71;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C: u16 = 72;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_CL: u16 = 73;
/// Load 2 horizontal elements from a user-specified miplevel in an image surface and store the result into a vector regi...
pub const IMAGE_LOAD_MIP_BY2: u16 = 74;
/// Load 4 horizontal elements from a user-specified miplevel in an image surface and store the result into a vector regi...
pub const IMAGE_LOAD_MIP_BY4: u16 = 75;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_L: u16 = 76;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_B: u16 = 77;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_B_CL: u16 = 78;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_LZ: u16 = 79;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_O: u16 = 80;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_CL_O: u16 = 81;
/// Store 2 horizontal elements from a vector register to the largest miplevel in an image surface. The texel data is con...
pub const IMAGE_STORE_BY2: u16 = 82;
/// Store 4 horizontal elements from a vector register to the largest miplevel in an image surface. The texel data is con...
pub const IMAGE_STORE_BY4: u16 = 83;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_L_O: u16 = 84;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_B_O: u16 = 85;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_B_CL_O: u16 = 86;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_LZ_O: u16 = 87;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_O: u16 = 88;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_CL_O: u16 = 89;
/// Store 2 horizontal elements from a vector register to a user-specified miplevel in an image surface. The texel data i...
pub const IMAGE_STORE_MIP_BY2: u16 = 90;
/// Store 4 horizontal elements from a vector register to a user-specified miplevel in an image surface. The texel data i...
pub const IMAGE_STORE_MIP_BY4: u16 = 91;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_L_O: u16 = 92;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_B_O: u16 = 93;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_B_CL_O: u16 = 94;
/// Gather 4 single-component texels from a 2x2 matrix on an image surface. Store the result into vector registers. The D...
pub const IMAGE_GATHER4_C_LZ_O: u16 = 95;
/// Return the calculated level of detail (LOD) for the provided input as two single-precision float values. No memory ac...
pub const IMAGE_GET_LOD: u16 = 96;
/// Gather 4 single-component texels from a 4x1 row vector on an image surface. Store the result into vector registers. T...
pub const IMAGE_GATHER4H: u16 = 97;
/// Gather all components of 4 texels from a 4x1 row vector on an image surface. Store the result into vector registers. ...
pub const IMAGE_GATHER4H_PCK: u16 = 98;
/// Gather all components of 8 texels from a 8x1 row vector on an image surface. Store the result into vector registers. ...
pub const IMAGE_GATHER8H_PCK: u16 = 99;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD: u16 = 104;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD_CL: u16 = 105;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD: u16 = 106;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD_CL: u16 = 107;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD_O: u16 = 108;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD_CL_O: u16 = 109;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD_O: u16 = 110;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD_CL_O: u16 = 111;
/// Load 2 horizontal elements from the largest miplevel in an image surface and store the result into a vector register....
pub const IMAGE_LOAD_PCK2: u16 = 112;
/// Load 4 horizontal elements from the largest miplevel in an image surface and store the result into a vector register....
pub const IMAGE_LOAD_PCK4: u16 = 113;
/// Load 2 horizontal elements from a user-specified miplevel in an image surface and store the result into a vector regi...
pub const IMAGE_LOAD_MIP_PCK2: u16 = 115;
/// Load 4 horizontal elements from a user-specified miplevel in an image surface and store the result into a vector regi...
pub const IMAGE_LOAD_MIP_PCK4: u16 = 116;
/// Store 2 horizontal elements from a vector register to the largest miplevel in an image surface. The texel data is alr...
pub const IMAGE_STORE_PCK2: u16 = 118;
/// Store 4 horizontal elements from a vector register to the largest miplevel in an image surface. The texel data is alr...
pub const IMAGE_STORE_PCK4: u16 = 119;
/// Store 2 horizontal elements from a vector register to a user-specified miplevel in an image surface. The texel data i...
pub const IMAGE_STORE_MIP_PCK2: u16 = 121;
/// Store 4 horizontal elements from a vector register to a user-specified miplevel in an image surface. The texel data i...
pub const IMAGE_STORE_MIP_PCK4: u16 = 122;
/// Load up to 4 samples of 1 component from an MSAA resource with a user-specified fragment ID. No sampling is performed.
pub const IMAGE_MSAA_LOAD: u16 = 128;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D_G16: u16 = 162;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D_CL_G16: u16 = 163;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D_G16: u16 = 170;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D_CL_G16: u16 = 171;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D_O_G16: u16 = 178;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_D_CL_O_G16: u16 = 179;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D_O_G16: u16 = 186;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_D_CL_O_G16: u16 = 187;
/// Test the intersection of rays with either box nodes or triangle nodes within a bounded volume hierarchy using 32 bit ...
pub const IMAGE_BVH_INTERSECT_RAY: u16 = 230;
/// Test the intersection of rays with either box nodes or triangle nodes within a bounded volume hierarchy using 64 bit ...
pub const IMAGE_BVH64_INTERSECT_RAY: u16 = 231;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD_G16: u16 = 232;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD_CL_G16: u16 = 233;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD_G16: u16 = 234;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD_CL_G16: u16 = 235;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD_O_G16: u16 = 236;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_CD_CL_O_G16: u16 = 237;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD_O_G16: u16 = 238;
/// Sample texels from an image surface using texel coordinates provided by the address input registers and store the res...
pub const IMAGE_SAMPLE_C_CD_CL_O_G16: u16 = 239;

