// SPDX-License-Identifier: AGPL-3.0-only
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::super::isa_types::InstrEntry;

/// All ENC_MIMG instructions.
pub const TABLE: &[InstrEntry] = &[
    InstrEntry {
        name: "IMAGE_LOAD",
        opcode: 0,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_MIP",
        opcode: 1,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_PCK",
        opcode: 2,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_PCK_SGN",
        opcode: 3,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_MIP_PCK",
        opcode: 4,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_MIP_PCK_SGN",
        opcode: 5,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE",
        opcode: 8,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_MIP",
        opcode: 9,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_PCK",
        opcode: 10,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_MIP_PCK",
        opcode: 11,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GET_RESINFO",
        opcode: 14,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_SWAP",
        opcode: 15,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_CMPSWAP",
        opcode: 16,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_ADD",
        opcode: 17,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_SUB",
        opcode: 18,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_SMIN",
        opcode: 20,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_UMIN",
        opcode: 21,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_SMAX",
        opcode: 22,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_UMAX",
        opcode: 23,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_AND",
        opcode: 24,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_OR",
        opcode: 25,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_XOR",
        opcode: 26,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_INC",
        opcode: 27,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_DEC",
        opcode: 28,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_FCMPSWAP",
        opcode: 29,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_FMIN",
        opcode: 30,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_ATOMIC_FMAX",
        opcode: 31,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE",
        opcode: 32,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CL",
        opcode: 33,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D",
        opcode: 34,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D_CL",
        opcode: 35,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_L",
        opcode: 36,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_B",
        opcode: 37,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_B_CL",
        opcode: 38,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_LZ",
        opcode: 39,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C",
        opcode: 40,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CL",
        opcode: 41,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D",
        opcode: 42,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D_CL",
        opcode: 43,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_L",
        opcode: 44,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_B",
        opcode: 45,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_B_CL",
        opcode: 46,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_LZ",
        opcode: 47,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_O",
        opcode: 48,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CL_O",
        opcode: 49,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D_O",
        opcode: 50,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D_CL_O",
        opcode: 51,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_L_O",
        opcode: 52,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_B_O",
        opcode: 53,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_B_CL_O",
        opcode: 54,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_LZ_O",
        opcode: 55,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_O",
        opcode: 56,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CL_O",
        opcode: 57,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D_O",
        opcode: 58,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D_CL_O",
        opcode: 59,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_L_O",
        opcode: 60,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_B_O",
        opcode: 61,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_B_CL_O",
        opcode: 62,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_LZ_O",
        opcode: 63,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4",
        opcode: 64,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_CL",
        opcode: 65,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_BY2",
        opcode: 66,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_BY4",
        opcode: 67,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_L",
        opcode: 68,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_B",
        opcode: 69,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_B_CL",
        opcode: 70,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_LZ",
        opcode: 71,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C",
        opcode: 72,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_CL",
        opcode: 73,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_MIP_BY2",
        opcode: 74,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_MIP_BY4",
        opcode: 75,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_L",
        opcode: 76,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_B",
        opcode: 77,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_B_CL",
        opcode: 78,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_LZ",
        opcode: 79,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_O",
        opcode: 80,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_CL_O",
        opcode: 81,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_BY2",
        opcode: 82,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_BY4",
        opcode: 83,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_L_O",
        opcode: 84,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_B_O",
        opcode: 85,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_B_CL_O",
        opcode: 86,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_LZ_O",
        opcode: 87,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_O",
        opcode: 88,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_CL_O",
        opcode: 89,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_MIP_BY2",
        opcode: 90,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_MIP_BY4",
        opcode: 91,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_L_O",
        opcode: 92,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_B_O",
        opcode: 93,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_B_CL_O",
        opcode: 94,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4_C_LZ_O",
        opcode: 95,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GET_LOD",
        opcode: 96,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4H",
        opcode: 97,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER4H_PCK",
        opcode: 98,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_GATHER8H_PCK",
        opcode: 99,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD",
        opcode: 104,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD_CL",
        opcode: 105,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD",
        opcode: 106,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD_CL",
        opcode: 107,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD_O",
        opcode: 108,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD_CL_O",
        opcode: 109,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD_O",
        opcode: 110,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD_CL_O",
        opcode: 111,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_PCK2",
        opcode: 112,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_PCK4",
        opcode: 113,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_MIP_PCK2",
        opcode: 115,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_LOAD_MIP_PCK4",
        opcode: 116,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_PCK2",
        opcode: 118,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_PCK4",
        opcode: 119,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_MIP_PCK2",
        opcode: 121,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_STORE_MIP_PCK4",
        opcode: 122,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_MSAA_LOAD",
        opcode: 128,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D_G16",
        opcode: 162,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D_CL_G16",
        opcode: 163,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D_G16",
        opcode: 170,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D_CL_G16",
        opcode: 171,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D_O_G16",
        opcode: 178,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_D_CL_O_G16",
        opcode: 179,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D_O_G16",
        opcode: 186,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_D_CL_O_G16",
        opcode: 187,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_BVH_INTERSECT_RAY",
        opcode: 230,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_BVH64_INTERSECT_RAY",
        opcode: 231,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD_G16",
        opcode: 232,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD_CL_G16",
        opcode: 233,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD_G16",
        opcode: 234,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD_CL_G16",
        opcode: 235,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD_O_G16",
        opcode: 236,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_CD_CL_O_G16",
        opcode: 237,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD_O_G16",
        opcode: 238,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "IMAGE_SAMPLE_C_CD_CL_O_G16",
        opcode: 239,
        is_branch: false,
        is_terminator: false,
    },
];

/// Look up an instruction by opcode.
#[must_use]
pub fn lookup(opcode: u16) -> Option<&'static InstrEntry> {
    TABLE.iter().find(|e| e.opcode == opcode)
}
