// SPDX-License-Identifier: AGPL-3.0-only
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::isa_types::{BitField, InstrEntry};
mod table;
pub use table::{TABLE, lookup};

/// ENC_VOPC encoding fields (32 bits).
pub mod fields {
    use super::BitField;
    pub const SRC0: BitField = BitField {
        offset: 0,
        width: 9,
    };
    pub const VSRC1: BitField = BitField {
        offset: 9,
        width: 8,
    };
    pub const OP: BitField = BitField {
        offset: 17,
        width: 8,
    };
    pub const ENCODING: BitField = BitField {
        offset: 25,
        width: 7,
    };
}

/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_F32: u16 = 0;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_F32: u16 = 1;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_F32: u16 = 2;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_F32: u16 = 3;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_F32: u16 = 4;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMP_LG_F32: u16 = 5;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_F32: u16 = 6;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into VCC or...
pub const V_CMP_O_F32: u16 = 7;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into VC...
pub const V_CMP_U_F32: u16 = 8;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMP_NGE_F32: u16 = 9;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMP_NLG_F32: u16 = 10;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into VC...
pub const V_CMP_NGT_F32: u16 = 11;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMP_NLE_F32: u16 = 12;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NEQ_F32: u16 = 13;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into VCC o...
pub const V_CMP_NLT_F32: u16 = 14;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_TRU_F32: u16 = 15;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_F32: u16 = 16;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_F32: u16 = 17;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_F32: u16 = 18;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_F32: u16 = 19;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_F32: u16 = 20;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMPX_LG_F32: u16 = 21;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_F32: u16 = 22;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into the EX...
pub const V_CMPX_O_F32: u16 = 23;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into th...
pub const V_CMPX_U_F32: u16 = 24;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMPX_NGE_F32: u16 = 25;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMPX_NLG_F32: u16 = 26;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into th...
pub const V_CMPX_NGT_F32: u16 = 27;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMPX_NLE_F32: u16 = 28;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NEQ_F32: u16 = 29;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into the E...
pub const V_CMPX_NLT_F32: u16 = 30;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_TRU_F32: u16 = 31;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_F64: u16 = 32;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_F64: u16 = 33;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_F64: u16 = 34;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_F64: u16 = 35;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_F64: u16 = 36;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMP_LG_F64: u16 = 37;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_F64: u16 = 38;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into VCC or...
pub const V_CMP_O_F64: u16 = 39;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into VC...
pub const V_CMP_U_F64: u16 = 40;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMP_NGE_F64: u16 = 41;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMP_NLG_F64: u16 = 42;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into VC...
pub const V_CMP_NGT_F64: u16 = 43;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMP_NLE_F64: u16 = 44;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NEQ_F64: u16 = 45;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into VCC o...
pub const V_CMP_NLT_F64: u16 = 46;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_TRU_F64: u16 = 47;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_F64: u16 = 48;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_F64: u16 = 49;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_F64: u16 = 50;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_F64: u16 = 51;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_F64: u16 = 52;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMPX_LG_F64: u16 = 53;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_F64: u16 = 54;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into the EX...
pub const V_CMPX_O_F64: u16 = 55;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into th...
pub const V_CMPX_U_F64: u16 = 56;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMPX_NGE_F64: u16 = 57;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMPX_NLG_F64: u16 = 58;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into th...
pub const V_CMPX_NGT_F64: u16 = 59;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMPX_NLE_F64: u16 = 60;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NEQ_F64: u16 = 61;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into the E...
pub const V_CMPX_NLT_F64: u16 = 62;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_TRU_F64: u16 = 63;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_I32: u16 = 128;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_I32: u16 = 129;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_I32: u16 = 130;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_I32: u16 = 131;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_I32: u16 = 132;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_I32: u16 = 133;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_I32: u16 = 134;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_I32: u16 = 135;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a single-...
pub const V_CMP_CLASS_F32: u16 = 136;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_I16: u16 = 137;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_I16: u16 = 138;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_I16: u16 = 139;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_I16: u16 = 140;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_I16: u16 = 141;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_I16: u16 = 142;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a half-pr...
pub const V_CMP_CLASS_F16: u16 = 143;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_I32: u16 = 144;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_I32: u16 = 145;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_I32: u16 = 146;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_I32: u16 = 147;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_I32: u16 = 148;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_I32: u16 = 149;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_I32: u16 = 150;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_I32: u16 = 151;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a single-...
pub const V_CMPX_CLASS_F32: u16 = 152;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_I16: u16 = 153;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_I16: u16 = 154;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_I16: u16 = 155;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_I16: u16 = 156;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_I16: u16 = 157;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_I16: u16 = 158;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a half-pr...
pub const V_CMPX_CLASS_F16: u16 = 159;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_I64: u16 = 160;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_I64: u16 = 161;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_I64: u16 = 162;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_I64: u16 = 163;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_I64: u16 = 164;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_I64: u16 = 165;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_I64: u16 = 166;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_I64: u16 = 167;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a double-...
pub const V_CMP_CLASS_F64: u16 = 168;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_U16: u16 = 169;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_U16: u16 = 170;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_U16: u16 = 171;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_U16: u16 = 172;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_U16: u16 = 173;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_U16: u16 = 174;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_I64: u16 = 176;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_I64: u16 = 177;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_I64: u16 = 178;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_I64: u16 = 179;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_I64: u16 = 180;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_I64: u16 = 181;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_I64: u16 = 182;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_I64: u16 = 183;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a double-...
pub const V_CMPX_CLASS_F64: u16 = 184;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_U16: u16 = 185;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_U16: u16 = 186;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_U16: u16 = 187;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_U16: u16 = 188;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_U16: u16 = 189;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_U16: u16 = 190;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_U32: u16 = 192;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_U32: u16 = 193;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_U32: u16 = 194;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_U32: u16 = 195;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_U32: u16 = 196;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_U32: u16 = 197;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_U32: u16 = 198;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_U32: u16 = 199;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_F16: u16 = 200;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_F16: u16 = 201;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_F16: u16 = 202;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_F16: u16 = 203;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_F16: u16 = 204;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMP_LG_F16: u16 = 205;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_F16: u16 = 206;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into VCC or...
pub const V_CMP_O_F16: u16 = 207;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_U32: u16 = 208;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_U32: u16 = 209;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_U32: u16 = 210;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_U32: u16 = 211;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_U32: u16 = 212;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_U32: u16 = 213;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_U32: u16 = 214;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_U32: u16 = 215;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_F16: u16 = 216;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_F16: u16 = 217;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_F16: u16 = 218;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_F16: u16 = 219;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_F16: u16 = 220;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMPX_LG_F16: u16 = 221;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_F16: u16 = 222;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into the EX...
pub const V_CMPX_O_F16: u16 = 223;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_U64: u16 = 224;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_U64: u16 = 225;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_U64: u16 = 226;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_U64: u16 = 227;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_U64: u16 = 228;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_U64: u16 = 229;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_U64: u16 = 230;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_U64: u16 = 231;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into VC...
pub const V_CMP_U_F16: u16 = 232;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMP_NGE_F16: u16 = 233;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMP_NLG_F16: u16 = 234;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into VC...
pub const V_CMP_NGT_F16: u16 = 235;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMP_NLE_F16: u16 = 236;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NEQ_F16: u16 = 237;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into VCC o...
pub const V_CMP_NLT_F16: u16 = 238;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_TRU_F16: u16 = 239;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_U64: u16 = 240;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_U64: u16 = 241;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_U64: u16 = 242;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_U64: u16 = 243;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_U64: u16 = 244;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_U64: u16 = 245;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_U64: u16 = 246;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_U64: u16 = 247;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into th...
pub const V_CMPX_U_F16: u16 = 248;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMPX_NGE_F16: u16 = 249;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMPX_NLG_F16: u16 = 250;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into th...
pub const V_CMPX_NGT_F16: u16 = 251;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMPX_NLE_F16: u16 = 252;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NEQ_F16: u16 = 253;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into the E...
pub const V_CMPX_NLT_F16: u16 = 254;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_TRU_F16: u16 = 255;
