// SPDX-License-Identifier: AGPL-3.0-only
//! PMC engine control and PTOP device table scanning for SEC2.

use crate::error::{DriverError, DriverResult};
use crate::vfio::channel::registers::misc;
use crate::vfio::device::MappedBar;

/// PMC enable for SEC2 engine (Nouveau: `nvkm_mc_enable`).
///
/// This is called AFTER the falcon-local ENGCTL reset to re-enable the
/// engine clock. Nouveau's `gm200_flcn_enable` does this as step 2,
/// after `reset_eng` and before `reset_wait_mem_scrubbing`.
///
/// Only ENABLES the engine — does not disable first. A full PMC
/// disable+enable cycle is a separate, more invasive operation.
pub(crate) fn pmc_enable_sec2(bar0: &MappedBar) -> DriverResult<()> {
    let sec2_bit = match find_sec2_pmc_bit(bar0) {
        Some(b) => b,
        None => {
            tracing::warn!("SEC2 PMC bit unknown — skipping PMC enable");
            return Ok(());
        }
    };
    let sec2_mask = 1u32 << sec2_bit;

    let val = bar0.read_u32(misc::PMC_ENABLE).unwrap_or(0);
    let already_enabled = val & sec2_mask != 0;
    tracing::info!(
        pmc_enable = format!("{val:#010x}"),
        sec2_bit,
        already_enabled,
        "PMC SEC2 enable (post-reset)"
    );

    if !already_enabled {
        bar0.write_u32(misc::PMC_ENABLE, val | sec2_mask)
            .map_err(|e| DriverError::SubmitFailed(format!("PMC enable SEC2: {e}").into()))?;
        let _ = bar0.read_u32(misc::PMC_ENABLE);
        std::thread::sleep(std::time::Duration::from_micros(20));
    }

    Ok(())
}

/// Full PMC disable+enable cycle for SEC2 (more invasive than `pmc_enable_sec2`).
/// Used by strategies that need a complete engine power cycle.
///
/// Includes PRI blind ACK after disable and after enable to clear any
/// cascading PRI routing faults generated by the clock domain transitions.
pub(crate) fn pmc_reset_sec2(bar0: &MappedBar) -> DriverResult<()> {
    const PRIV_RING_COMMAND: usize = 0x0012_004C;
    const PRIV_RING_CMD_ACK: u32 = 0x2;

    let sec2_bit = match find_sec2_pmc_bit(bar0) {
        Some(b) => b,
        None => {
            tracing::warn!("SEC2 PMC bit unknown — skipping PMC reset");
            return Ok(());
        }
    };
    let sec2_mask = 1u32 << sec2_bit;

    let val = bar0.read_u32(misc::PMC_ENABLE).unwrap_or(0);
    tracing::info!(
        pmc_enable = format!("{val:#010x}"),
        sec2_bit,
        sec2_mask = format!("{sec2_mask:#010x}"),
        sec2_enabled = val & sec2_mask != 0,
        "PMC SEC2 reset: disabling engine"
    );

    bar0.write_u32(misc::PMC_ENABLE, val & !sec2_mask)
        .map_err(|e| DriverError::SubmitFailed(format!("PMC disable SEC2: {e}").into()))?;
    let _ = bar0.read_u32(misc::PMC_ENABLE);
    std::thread::sleep(std::time::Duration::from_micros(20));
    let _ = bar0.write_u32(PRIV_RING_COMMAND, PRIV_RING_CMD_ACK);
    std::thread::sleep(std::time::Duration::from_millis(5));

    bar0.write_u32(misc::PMC_ENABLE, val | sec2_mask)
        .map_err(|e| DriverError::SubmitFailed(format!("PMC enable SEC2: {e}").into()))?;
    let _ = bar0.read_u32(misc::PMC_ENABLE);
    std::thread::sleep(std::time::Duration::from_micros(20));
    let _ = bar0.write_u32(PRIV_RING_COMMAND, PRIV_RING_CMD_ACK);
    std::thread::sleep(std::time::Duration::from_millis(5));

    let after = bar0.read_u32(misc::PMC_ENABLE).unwrap_or(0);
    tracing::info!(
        pmc_after = format!("{after:#010x}"),
        sec2_enabled = after & sec2_mask != 0,
        "PMC SEC2 reset: engine re-enabled + PRI ACKed"
    );

    Ok(())
}

/// Scan PTOP device info table at `0x22700` to find SEC2's PMC reset bit.
///
/// Matches nouveau's `gk104_top_parse` (GK104+ including GV100 Volta).
/// The table at `0x22700 + i*4` uses multi-entry sequences terminated by
/// bit 31 clear. Entry types (bits [1:0]):
///
///   - `0b00`: NOT_VALID (skip)
///   - `0b01`: DATA — bits [23:12] = MMIO addr, bit 2 set → bits [9:3] = fault ID
///   - `0b10`: ENUM — bit 2 set → bits [13:9] = PMC reset bit;
///                     bit 3 set → bits [18:15] = intr leaf;
///                     bit 4 set → bits [25:21] = runlist;
///                     bit 5 set → bits [29:26] = engine ID
///   - `0b11`: ENGINE_TYPE — bits [29:2] = engine type code
///             (bit 31 is the continuation flag, NOT part of the type)
///
/// Engine types (from nouveau `gk104_top_parse`):
///   0x00=GR, 0x01..0x03=CE, 0x0c=VIC, **0x0d=SEC2**, 0x14=GSP, 0x15=NVJPG
///
/// The PMC reset bit is `1 << info.reset` in NV_PMC_ENABLE (0x200).
///
/// **GV100 note**: SEC2 is NOT listed in PTOP on GV100 Titan V. When PTOP
/// lookup fails, [`sec2_pmc_bit_by_chip`] provides a per-generation fallback.
pub(crate) fn find_sec2_pmc_bit(bar0: &MappedBar) -> Option<u32> {
    if let Some(bit) = find_sec2_pmc_bit_ptop(bar0) {
        return Some(bit);
    }
    let fallback = sec2_pmc_bit_by_chip(bar0);
    tracing::info!(
        bit = ?fallback,
        "SEC2 not in PTOP — using chip-ID fallback"
    );
    fallback
}

/// PTOP scan for SEC2 engine (type 0x0d).
fn find_sec2_pmc_bit_ptop(bar0: &MappedBar) -> Option<u32> {
    const SEC2_ENGINE_TYPE: u32 = 0x0d;

    let mut current_type: u32 = 0xFFFF_FFFF;
    let mut current_reset: Option<u32> = None;

    for idx in 0..64u32 {
        let entry = bar0.read_u32(0x22700 + idx as usize * 4).unwrap_or(0);
        if entry == 0 {
            break;
        }
        let entry_kind = entry & 0x3;

        match entry_kind {
            0 => continue, // NOT_VALID
            1 => {
                // DATA: addr/fault — nothing we need for PMC bit
            }
            2 => {
                // ENUM: engine/runlist/intr/reset
                if entry & (1 << 2) != 0 {
                    let reset_bit = (entry >> 9) & 0x1F;
                    current_reset = Some(reset_bit);
                    tracing::trace!(
                        ptop_idx = idx,
                        entry = format!("{entry:#010x}"),
                        reset_bit,
                        "PTOP ENUM: reset bit"
                    );
                }
            }
            3 => {
                // ENGINE_TYPE: mask out bit 31 (continuation flag)
                current_type = (entry >> 2) & 0x1FFF_FFFF;
                tracing::trace!(
                    ptop_idx = idx,
                    entry = format!("{entry:#010x}"),
                    engine_type = format!("{current_type:#x}"),
                    "PTOP ENGINE_TYPE"
                );
            }
            _ => unreachable!(),
        }

        // Bit 31 clear = end of this device's entries → commit
        if entry & 0x8000_0000 == 0 {
            if current_type == SEC2_ENGINE_TYPE {
                if let Some(bit) = current_reset {
                    tracing::info!(
                        ptop_idx = idx,
                        engine_type = format!("{SEC2_ENGINE_TYPE:#x}"),
                        reset_bit = bit,
                        "PTOP: found SEC2 PMC reset bit"
                    );
                    return Some(bit);
                }
                tracing::warn!(
                    ptop_idx = idx,
                    "PTOP: found SEC2 engine but no reset bit in ENUM"
                );
            }
            // Reset per-device state for next device
            current_type = 0xFFFF_FFFF;
            current_reset = None;
        }
    }

    tracing::debug!("SEC2 (engine type {SEC2_ENGINE_TYPE:#x}) not found in PTOP table");
    None
}

/// Per-chip-family SEC2 PMC bit lookup for GPUs where SEC2 is absent from PTOP.
///
/// BOOT0 bits [31:20] encode the chip ID. Verified by live register probing:
/// - GV100 (Titan V): SEC2 at PMC bit 5 (confirmed: clearing bit 5 causes
///   SEC2 registers to return PRI errors `0xbad0da00`).
///
/// GP10x family uses bit 22 per envytools / community documentation.
fn sec2_pmc_bit_by_chip(bar0: &MappedBar) -> Option<u32> {
    let boot0 = bar0.read_u32(0x000).unwrap_or(0);
    let chip_id = (boot0 >> 20) & 0xFFF;
    tracing::debug!(boot0 = format!("{boot0:#010x}"), chip_id = format!("{chip_id:#x}"), "chip ID for SEC2 PMC fallback");

    match chip_id {
        // GV100 (Titan V) — confirmed via live probe
        0x140 => Some(5),
        // GP102..GP108 (Pascal) — conventional bit 22
        0x132..=0x138 => Some(22),
        // TU10x (Turing)
        0x164..=0x168 => Some(5),
        _ => {
            tracing::warn!(
                chip_id = format!("{chip_id:#x}"),
                "unknown chip — no SEC2 PMC bit fallback"
            );
            None
        }
    }
}
