// SPDX-License-Identifier: AGPL-3.0-only
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::super::isa_types::InstrEntry;

/// All ENC_DS instructions.
pub const TABLE: &[InstrEntry] = &[
    InstrEntry { name: "DS_ADD_U32", opcode: 0, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_SUB_U32", opcode: 1, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_RSUB_U32", opcode: 2, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_INC_U32", opcode: 3, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_DEC_U32", opcode: 4, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_I32", opcode: 5, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_I32", opcode: 6, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_U32", opcode: 7, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_U32", opcode: 8, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_AND_B32", opcode: 9, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_OR_B32", opcode: 10, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_XOR_B32", opcode: 11, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MSKOR_B32", opcode: 12, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B32", opcode: 13, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE2_B32", opcode: 14, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE2ST64_B32", opcode: 15, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_B32", opcode: 16, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_F32", opcode: 17, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_F32", opcode: 18, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_F32", opcode: 19, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_NOP", opcode: 20, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_ADD_F32", opcode: 21, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_GWS_SEMA_RELEASE_ALL", opcode: 24, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_GWS_INIT", opcode: 25, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_GWS_SEMA_V", opcode: 26, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_GWS_SEMA_BR", opcode: 27, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_GWS_SEMA_P", opcode: 28, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_GWS_BARRIER", opcode: 29, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B8", opcode: 30, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B16", opcode: 31, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_ADD_RTN_U32", opcode: 32, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_SUB_RTN_U32", opcode: 33, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_RSUB_RTN_U32", opcode: 34, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_INC_RTN_U32", opcode: 35, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_DEC_RTN_U32", opcode: 36, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_RTN_I32", opcode: 37, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_RTN_I32", opcode: 38, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_RTN_U32", opcode: 39, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_RTN_U32", opcode: 40, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_AND_RTN_B32", opcode: 41, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_OR_RTN_B32", opcode: 42, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_XOR_RTN_B32", opcode: 43, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MSKOR_RTN_B32", opcode: 44, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRXCHG_RTN_B32", opcode: 45, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRXCHG2_RTN_B32", opcode: 46, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRXCHG2ST64_RTN_B32", opcode: 47, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_RTN_B32", opcode: 48, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_RTN_F32", opcode: 49, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_RTN_F32", opcode: 50, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_RTN_F32", opcode: 51, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRAP_RTN_B32", opcode: 52, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_SWIZZLE_B32", opcode: 53, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_B32", opcode: 54, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ2_B32", opcode: 55, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ2ST64_B32", opcode: 56, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_I8", opcode: 57, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_U8", opcode: 58, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_I16", opcode: 59, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_U16", opcode: 60, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CONSUME", opcode: 61, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_APPEND", opcode: 62, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_ORDERED_COUNT", opcode: 63, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_ADD_U64", opcode: 64, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_SUB_U64", opcode: 65, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_RSUB_U64", opcode: 66, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_INC_U64", opcode: 67, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_DEC_U64", opcode: 68, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_I64", opcode: 69, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_I64", opcode: 70, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_U64", opcode: 71, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_U64", opcode: 72, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_AND_B64", opcode: 73, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_OR_B64", opcode: 74, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_XOR_B64", opcode: 75, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MSKOR_B64", opcode: 76, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B64", opcode: 77, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE2_B64", opcode: 78, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE2ST64_B64", opcode: 79, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_B64", opcode: 80, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_F64", opcode: 81, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_F64", opcode: 82, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_F64", opcode: 83, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_ADD_RTN_F32", opcode: 85, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_ADD_RTN_U64", opcode: 96, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_SUB_RTN_U64", opcode: 97, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_RSUB_RTN_U64", opcode: 98, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_INC_RTN_U64", opcode: 99, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_DEC_RTN_U64", opcode: 100, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_RTN_I64", opcode: 101, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_RTN_I64", opcode: 102, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_RTN_U64", opcode: 103, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_RTN_U64", opcode: 104, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_AND_RTN_B64", opcode: 105, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_OR_RTN_B64", opcode: 106, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_XOR_RTN_B64", opcode: 107, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MSKOR_RTN_B64", opcode: 108, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRXCHG_RTN_B64", opcode: 109, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRXCHG2_RTN_B64", opcode: 110, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRXCHG2ST64_RTN_B64", opcode: 111, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_RTN_B64", opcode: 112, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CMPST_RTN_F64", opcode: 113, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MIN_RTN_F64", opcode: 114, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_MAX_RTN_F64", opcode: 115, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_B64", opcode: 118, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ2_B64", opcode: 119, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ2ST64_B64", opcode: 120, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_CONDXCHG32_RTN_B64", opcode: 126, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B8_D16_HI", opcode: 160, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B16_D16_HI", opcode: 161, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_U8_D16", opcode: 162, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_U8_D16_HI", opcode: 163, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_I8_D16", opcode: 164, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_I8_D16_HI", opcode: 165, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_U16_D16", opcode: 166, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_U16_D16_HI", opcode: 167, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_ADDTID_B32", opcode: 176, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_ADDTID_B32", opcode: 177, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_PERMUTE_B32", opcode: 178, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_BPERMUTE_B32", opcode: 179, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B96", opcode: 222, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_WRITE_B128", opcode: 223, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_B96", opcode: 254, is_branch: false, is_terminator: false },
    InstrEntry { name: "DS_READ_B128", opcode: 255, is_branch: false, is_terminator: false },
];

/// Look up an instruction by opcode.
#[must_use]
pub fn lookup(opcode: u16) -> Option<&'static InstrEntry> {
    TABLE.iter().find(|e| e.opcode == opcode)
}
