// SPDX-License-Identifier: AGPL-3.0-only
//! DRM isolation — auto-generate udev rules and Xorg config from device list.
//!
//! When ember manages compute GPUs, those GPUs must be isolated from the
//! desktop compositor:
//!
//! 1. **udev rules** prevent `logind` from assigning the DRM node to `seat0`,
//!    which would cause gnome-shell to try (and fail) to configure a display.
//! 2. **Xorg ServerFlags** disable `AutoAddGPU` so Xorg doesn't hotplug
//!    newly-appearing DRM devices after a driver swap.
//!
//! This module generates both files from the device configuration, so the
//! isolation stays in sync with hardware changes automatically.

use crate::EmberDeviceConfig;

const UDEV_HEADER: &str = "\
# coralReef: DRM isolation for compute GPUs (auto-generated by coral-ember)
#
# Runs at 61 — BEFORE systemd logind (70-uaccess.rules, 73-seat-late.rules)
# so seat tags are never assigned in the first place.
#
# DO NOT EDIT — regenerated each time coral-ember starts.
";

const XORG_CONTENT: &str = "\
# coralReef: GPU isolation (auto-generated by coral-ember)
#
# Prevents Xorg from hotplugging compute GPUs managed by ember/glowplug.
# The display GPU is configured explicitly by the vendor OutputClass.
#
# DO NOT EDIT — regenerated each time coral-ember starts.

Section \"ServerFlags\"
    Option \"AutoAddGPU\" \"false\"
    Option \"AutoBindGPU\" \"false\"
EndSection
";

/// Default paths for DRM isolation files.
pub fn default_udev_path() -> String {
    std::env::var("CORALREEF_UDEV_ISOLATION_RULES")
        .unwrap_or_else(|_| "/etc/udev/rules.d/61-coralreef-drm-ignore.rules".to_string())
}

/// Default Xorg config path.
pub fn default_xorg_path() -> String {
    std::env::var("CORALREEF_XORG_ISOLATION_CONF")
        .ok()
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "/etc/X11/xorg.conf.d/11-coralreef-gpu-isolation.conf".to_string())
}

/// Generate a udev rules file body from the device list.
/// Display-role devices are excluded — they need their DRM nodes for compositing.
fn generate_udev_rules(devices: &[EmberDeviceConfig]) -> String {
    let mut out = String::from(UDEV_HEADER);
    for dev in devices {
        if dev.is_protected() {
            continue;
        }
        let name = dev.name.as_deref().unwrap_or("compute GPU");
        out.push_str(&format!(
            "\n# {} ({})\n\
             SUBSYSTEM==\"drm\", KERNELS==\"{}\", \
             ENV{{ID_SEAT}}=\"\", ENV{{ID_FOR_SEAT}}=\"\", \
             TAG-=\"seat\", TAG-=\"master-of-seat\", TAG-=\"uaccess\"\n",
            name, dev.bdf, dev.bdf,
        ));
    }
    out
}

/// Write DRM isolation files (udev + xorg) for the given device list.
///
/// Returns a list of paths that were successfully written.
/// Failures are logged but not fatal — ember can run without isolation,
/// though driver swaps to DRM drivers will be blocked by
/// `verify_drm_isolation` until the files are in place.
pub fn ensure_drm_isolation(devices: &[EmberDeviceConfig]) -> Vec<String> {
    let mut written = Vec::new();

    let udev_path = default_udev_path();
    let udev_content = generate_udev_rules(devices);
    match write_if_changed(&udev_path, &udev_content) {
        Ok(true) => {
            tracing::info!(path = %udev_path, devices = devices.len(), "udev DRM isolation rules updated");
            reload_udev();
            written.push(udev_path);
        }
        Ok(false) => {
            tracing::debug!(path = %udev_path, "udev DRM isolation rules unchanged");
        }
        Err(e) => {
            tracing::warn!(path = %udev_path, error = %e, "failed to write udev DRM isolation rules");
        }
    }

    let xorg_path = default_xorg_path();
    match write_if_changed(&xorg_path, XORG_CONTENT) {
        Ok(true) => {
            tracing::info!(path = %xorg_path, "Xorg GPU isolation config updated");
            written.push(xorg_path);
        }
        Ok(false) => {
            tracing::debug!(path = %xorg_path, "Xorg GPU isolation config unchanged");
        }
        Err(e) => {
            tracing::warn!(path = %xorg_path, error = %e, "failed to write Xorg GPU isolation config");
        }
    }

    written
}

/// Write content only if the file doesn't exist or has different content.
/// Returns `Ok(true)` if written, `Ok(false)` if unchanged.
fn write_if_changed(path: &str, content: &str) -> Result<bool, std::io::Error> {
    if let Ok(existing) = std::fs::read_to_string(path) {
        if existing == content {
            return Ok(false);
        }
    }
    if let Some(parent) = std::path::Path::new(path).parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(true)
}

fn reload_udev() {
    match std::process::Command::new("udevadm")
        .args(["control", "--reload-rules"])
        .output()
    {
        Ok(out) if out.status.success() => {
            tracing::debug!("udevadm reload-rules succeeded");
        }
        Ok(out) => {
            let stderr = String::from_utf8_lossy(&out.stderr);
            tracing::debug!(%stderr, "udevadm reload-rules failed (non-fatal)");
        }
        Err(e) => {
            tracing::debug!(error = %e, "udevadm not available (non-fatal)");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_device(bdf: &str, name: &str) -> EmberDeviceConfig {
        EmberDeviceConfig {
            bdf: bdf.to_string(),
            name: Some(name.to_string()),
            boot_personality: Some("vfio".to_string()),
            power_policy: None,
            role: None,
            oracle_dump: None,
        }
    }

    #[test]
    fn generate_udev_rules_includes_all_devices() {
        let devices = vec![
            test_device("0000:03:00.0", "titan-v-1"),
            test_device("0000:4b:00.0", "titan-v-2"),
        ];
        let rules = generate_udev_rules(&devices);
        assert!(rules.contains("KERNELS==\"0000:03:00.0\""));
        assert!(rules.contains("KERNELS==\"0000:4b:00.0\""));
        assert!(rules.contains("TAG-=\"seat\""));
        assert!(rules.contains("titan-v-1"));
        assert!(rules.contains("titan-v-2"));
        assert!(rules.contains("auto-generated"));
    }

    #[test]
    fn generate_udev_rules_empty_devices() {
        let rules = generate_udev_rules(&[]);
        assert!(rules.contains("auto-generated"));
        assert!(!rules.contains("KERNELS"));
    }

    #[test]
    fn generate_udev_rules_unnamed_device() {
        let devices = vec![EmberDeviceConfig {
            bdf: "0000:01:00.0".to_string(),
            name: None,
            boot_personality: None,
            power_policy: None,
            role: None,
            oracle_dump: None,
        }];
        let rules = generate_udev_rules(&devices);
        assert!(rules.contains("compute GPU"));
        assert!(rules.contains("0000:01:00.0"));
    }

    #[test]
    fn write_if_changed_creates_new_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test-rules");
        let written = write_if_changed(path.to_str().unwrap(), "content").unwrap();
        assert!(written);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "content");
    }

    #[test]
    fn write_if_changed_skips_identical() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test-rules");
        std::fs::write(&path, "content").unwrap();
        let written = write_if_changed(path.to_str().unwrap(), "content").unwrap();
        assert!(!written);
    }

    #[test]
    fn write_if_changed_updates_different() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test-rules");
        std::fs::write(&path, "old").unwrap();
        let written = write_if_changed(path.to_str().unwrap(), "new").unwrap();
        assert!(written);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "new");
    }

    #[test]
    fn xorg_content_has_auto_add_gpu_false() {
        assert!(XORG_CONTENT.contains("AutoAddGPU"));
        assert!(XORG_CONTENT.contains("false"));
        assert!(XORG_CONTENT.contains("AutoBindGPU"));
    }

    #[test]
    fn ensure_drm_isolation_unit_test_via_write_if_changed() {
        let dir = tempfile::tempdir().unwrap();
        let udev_path = dir.path().join("udev.rules");
        let xorg_path = dir.path().join("xorg.conf");

        let devices = vec![test_device("0000:03:00.0", "titan-v")];
        let udev_content = generate_udev_rules(&devices);
        write_if_changed(udev_path.to_str().unwrap(), &udev_content).unwrap();
        write_if_changed(xorg_path.to_str().unwrap(), XORG_CONTENT).unwrap();

        let udev_read = std::fs::read_to_string(&udev_path).unwrap();
        assert!(udev_read.contains("0000:03:00.0"));
        assert!(udev_read.contains("TAG-=\"seat\""));

        let xorg_read = std::fs::read_to_string(&xorg_path).unwrap();
        assert!(xorg_read.contains("AutoAddGPU"));
        assert!(xorg_read.contains("false"));
    }
}
