// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::isa_types::{BitField, InstrEntry};
mod table_arith;
mod table_cmp_f32_f64;
mod table_cmp_int;
mod table_logic;
mod table_math;

use std::sync::OnceLock;

static TABLE_CACHE: OnceLock<Vec<InstrEntry>> = OnceLock::new();

/// All ENC_VOP3 instructions (combined from sub-tables).
#[must_use]
pub fn table() -> &'static [InstrEntry] {
    TABLE_CACHE
        .get_or_init(|| {
            [
                table_cmp_f32_f64::TABLE,
                table_cmp_int::TABLE,
                table_math::TABLE,
                table_arith::TABLE,
                table_logic::TABLE,
            ]
            .concat()
        })
        .as_slice()
}

/// Look up an instruction by opcode.
#[must_use]
pub fn lookup(opcode: u16) -> Option<&'static InstrEntry> {
    table_cmp_f32_f64::lookup(opcode)
        .or_else(|| table_cmp_int::lookup(opcode))
        .or_else(|| table_math::lookup(opcode))
        .or_else(|| table_arith::lookup(opcode))
        .or_else(|| table_logic::lookup(opcode))
}

/// ENC_VOP3 encoding fields (64 bits).
pub mod fields {
    use super::BitField;
    pub const VDST: BitField = BitField {
        offset: 0,
        width: 8,
    };
    pub const ABS: BitField = BitField {
        offset: 8,
        width: 3,
    };
    pub const OP_SEL: BitField = BitField {
        offset: 11,
        width: 4,
    };
    pub const CLAMP: BitField = BitField {
        offset: 15,
        width: 1,
    };
    pub const OP: BitField = BitField {
        offset: 16,
        width: 10,
    };
    pub const ENCODING: BitField = BitField {
        offset: 26,
        width: 6,
    };
    pub const SRC0: BitField = BitField {
        offset: 32,
        width: 9,
    };
    pub const SRC1: BitField = BitField {
        offset: 41,
        width: 9,
    };
    pub const SRC2: BitField = BitField {
        offset: 50,
        width: 9,
    };
    pub const OMOD: BitField = BitField {
        offset: 59,
        width: 2,
    };
    pub const NEG: BitField = BitField {
        offset: 61,
        width: 3,
    };
}

/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_F32: u16 = 0;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_F32: u16 = 1;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_F32: u16 = 2;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_F32: u16 = 3;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_F32: u16 = 4;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMP_LG_F32: u16 = 5;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_F32: u16 = 6;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into VCC or...
pub const V_CMP_O_F32: u16 = 7;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into VC...
pub const V_CMP_U_F32: u16 = 8;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMP_NGE_F32: u16 = 9;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMP_NLG_F32: u16 = 10;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into VC...
pub const V_CMP_NGT_F32: u16 = 11;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMP_NLE_F32: u16 = 12;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NEQ_F32: u16 = 13;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into VCC o...
pub const V_CMP_NLT_F32: u16 = 14;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_TRU_F32: u16 = 15;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_F32: u16 = 16;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_F32: u16 = 17;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_F32: u16 = 18;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_F32: u16 = 19;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_F32: u16 = 20;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMPX_LG_F32: u16 = 21;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_F32: u16 = 22;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into the EX...
pub const V_CMPX_O_F32: u16 = 23;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into th...
pub const V_CMPX_U_F32: u16 = 24;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMPX_NGE_F32: u16 = 25;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMPX_NLG_F32: u16 = 26;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into th...
pub const V_CMPX_NGT_F32: u16 = 27;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMPX_NLE_F32: u16 = 28;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NEQ_F32: u16 = 29;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into the E...
pub const V_CMPX_NLT_F32: u16 = 30;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_TRU_F32: u16 = 31;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_F64: u16 = 32;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_F64: u16 = 33;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_F64: u16 = 34;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_F64: u16 = 35;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_F64: u16 = 36;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMP_LG_F64: u16 = 37;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_F64: u16 = 38;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into VCC or...
pub const V_CMP_O_F64: u16 = 39;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into VC...
pub const V_CMP_U_F64: u16 = 40;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMP_NGE_F64: u16 = 41;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMP_NLG_F64: u16 = 42;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into VC...
pub const V_CMP_NGT_F64: u16 = 43;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMP_NLE_F64: u16 = 44;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NEQ_F64: u16 = 45;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into VCC o...
pub const V_CMP_NLT_F64: u16 = 46;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_TRU_F64: u16 = 47;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_F64: u16 = 48;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_F64: u16 = 49;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_F64: u16 = 50;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_F64: u16 = 51;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_F64: u16 = 52;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMPX_LG_F64: u16 = 53;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_F64: u16 = 54;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into the EX...
pub const V_CMPX_O_F64: u16 = 55;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into th...
pub const V_CMPX_U_F64: u16 = 56;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMPX_NGE_F64: u16 = 57;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMPX_NLG_F64: u16 = 58;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into th...
pub const V_CMPX_NGT_F64: u16 = 59;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMPX_NLE_F64: u16 = 60;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NEQ_F64: u16 = 61;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into the E...
pub const V_CMPX_NLT_F64: u16 = 62;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_TRU_F64: u16 = 63;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_I32: u16 = 128;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_I32: u16 = 129;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_I32: u16 = 130;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_I32: u16 = 131;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_I32: u16 = 132;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_I32: u16 = 133;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_I32: u16 = 134;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_I32: u16 = 135;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a single-...
pub const V_CMP_CLASS_F32: u16 = 136;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_I16: u16 = 137;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_I16: u16 = 138;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_I16: u16 = 139;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_I16: u16 = 140;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_I16: u16 = 141;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_I16: u16 = 142;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a half-pr...
pub const V_CMP_CLASS_F16: u16 = 143;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_I32: u16 = 144;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_I32: u16 = 145;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_I32: u16 = 146;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_I32: u16 = 147;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_I32: u16 = 148;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_I32: u16 = 149;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_I32: u16 = 150;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_I32: u16 = 151;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a single-...
pub const V_CMPX_CLASS_F32: u16 = 152;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_I16: u16 = 153;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_I16: u16 = 154;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_I16: u16 = 155;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_I16: u16 = 156;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_I16: u16 = 157;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_I16: u16 = 158;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a half-pr...
pub const V_CMPX_CLASS_F16: u16 = 159;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_I64: u16 = 160;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_I64: u16 = 161;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_I64: u16 = 162;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_I64: u16 = 163;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_I64: u16 = 164;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_I64: u16 = 165;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_I64: u16 = 166;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_I64: u16 = 167;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a double-...
pub const V_CMP_CLASS_F64: u16 = 168;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_U16: u16 = 169;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_U16: u16 = 170;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_U16: u16 = 171;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_U16: u16 = 172;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_U16: u16 = 173;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_U16: u16 = 174;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_I64: u16 = 176;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_I64: u16 = 177;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_I64: u16 = 178;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_I64: u16 = 179;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_I64: u16 = 180;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_I64: u16 = 181;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_I64: u16 = 182;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_I64: u16 = 183;
/// Evaluate the IEEE numeric class function specified as a 10 bit mask in the second input on the first input, a double-...
pub const V_CMPX_CLASS_F64: u16 = 184;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_U16: u16 = 185;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_U16: u16 = 186;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_U16: u16 = 187;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_U16: u16 = 188;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_U16: u16 = 189;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_U16: u16 = 190;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_U32: u16 = 192;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_U32: u16 = 193;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_U32: u16 = 194;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_U32: u16 = 195;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_U32: u16 = 196;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_U32: u16 = 197;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_U32: u16 = 198;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_U32: u16 = 199;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_F16: u16 = 200;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_F16: u16 = 201;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_F16: u16 = 202;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_F16: u16 = 203;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_F16: u16 = 204;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMP_LG_F16: u16 = 205;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_F16: u16 = 206;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into VCC or...
pub const V_CMP_O_F16: u16 = 207;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_U32: u16 = 208;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_U32: u16 = 209;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_U32: u16 = 210;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_U32: u16 = 211;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_U32: u16 = 212;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_U32: u16 = 213;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_U32: u16 = 214;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_U32: u16 = 215;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_F16: u16 = 216;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_F16: u16 = 217;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_F16: u16 = 218;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_F16: u16 = 219;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_F16: u16 = 220;
/// Set the vector condition code to 1 iff the first input is less than or greater than the second input. Store the resul...
pub const V_CMPX_LG_F16: u16 = 221;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_F16: u16 = 222;
/// Set the vector condition code to 1 iff the first input is orderable to the second input. Store the result into the EX...
pub const V_CMPX_O_F16: u16 = 223;
/// Set the vector condition code to 0. Store the result into VCC or a scalar register.
pub const V_CMP_F_U64: u16 = 224;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into VCC or a ...
pub const V_CMP_LT_U64: u16 = 225;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into VCC or a s...
pub const V_CMP_EQ_U64: u16 = 226;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMP_LE_U64: u16 = 227;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into VCC or...
pub const V_CMP_GT_U64: u16 = 228;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NE_U64: u16 = 229;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMP_GE_U64: u16 = 230;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_T_U64: u16 = 231;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into VC...
pub const V_CMP_U_F16: u16 = 232;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMP_NGE_F16: u16 = 233;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMP_NLG_F16: u16 = 234;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into VC...
pub const V_CMP_NGT_F16: u16 = 235;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMP_NLE_F16: u16 = 236;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into VCC or...
pub const V_CMP_NEQ_F16: u16 = 237;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into VCC o...
pub const V_CMP_NLT_F16: u16 = 238;
/// Set the vector condition code to 1. Store the result into VCC or a scalar register.
pub const V_CMP_TRU_F16: u16 = 239;
/// Set the vector condition code to 0. Store the result into the EXEC mask.
pub const V_CMPX_F_U64: u16 = 240;
/// Set the vector condition code to 1 iff the first input is less than the second input. Store the result into the EXEC ...
pub const V_CMPX_LT_U64: u16 = 241;
/// Set the vector condition code to 1 iff the first input is equal to the second input. Store the result into the EXEC m...
pub const V_CMPX_EQ_U64: u16 = 242;
/// Set the vector condition code to 1 iff the first input is less than or equal to the second input. Store the result in...
pub const V_CMPX_LE_U64: u16 = 243;
/// Set the vector condition code to 1 iff the first input is greater than the second input. Store the result into the EX...
pub const V_CMPX_GT_U64: u16 = 244;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NE_U64: u16 = 245;
/// Set the vector condition code to 1 iff the first input is greater than or equal to the second input. Store the result...
pub const V_CMPX_GE_U64: u16 = 246;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_T_U64: u16 = 247;
/// Set the vector condition code to 1 iff the first input is not orderable to the second input. Store the result into th...
pub const V_CMPX_U_F16: u16 = 248;
/// Set the vector condition code to 1 iff the first input is not greater than or equal to the second input. Store the re...
pub const V_CMPX_NGE_F16: u16 = 249;
/// Set the vector condition code to 1 iff the first input is not less than or greater than the second input. Store the r...
pub const V_CMPX_NLG_F16: u16 = 250;
/// Set the vector condition code to 1 iff the first input is not greater than the second input. Store the result into th...
pub const V_CMPX_NGT_F16: u16 = 251;
/// Set the vector condition code to 1 iff the first input is not less than or equal to the second input. Store the resul...
pub const V_CMPX_NLE_F16: u16 = 252;
/// Set the vector condition code to 1 iff the first input is not equal to the second input. Store the result into the EX...
pub const V_CMPX_NEQ_F16: u16 = 253;
/// Set the vector condition code to 1 iff the first input is not less than the second input. Store the result into the E...
pub const V_CMPX_NLT_F16: u16 = 254;
/// Set the vector condition code to 1. Store the result into the EXEC mask.
pub const V_CMPX_TRU_F16: u16 = 255;
/// Copy data from one of two inputs based on the vector condition code and store the result into a vector register.
pub const V_CNDMASK_B32: u16 = 257;
/// Add two floating point inputs and store the result into a vector register.
pub const V_ADD_F32: u16 = 259;
/// Subtract the second floating point input from the first input and store the result into a vector register.
pub const V_SUB_F32: u16 = 260;
/// Subtract the first floating point input from the second input and store the result into a vector register.
pub const V_SUBREV_F32: u16 = 261;
/// Multiply two single-precision values and accumulate the result with the destination. Follows DX9 rules where 0.0 time...
pub const V_FMAC_LEGACY_F32: u16 = 262;
/// Multiply two floating point inputs and store the result in a vector register. Follows DX9 rules where 0.0 times anyth...
pub const V_MUL_LEGACY_F32: u16 = 263;
/// Multiply two floating point inputs and store the result into a vector register.
pub const V_MUL_F32: u16 = 264;
/// Multiply two signed 24-bit integer inputs and store the result as a signed 32-bit integer into a vector register.
pub const V_MUL_I32_I24: u16 = 265;
/// Multiply two signed 24-bit integer inputs and store the high 32 bits of the result as a signed 32-bit integer into a ...
pub const V_MUL_HI_I32_I24: u16 = 266;
/// Multiply two unsigned 24-bit integer inputs and store the result as an unsigned 32-bit integer into a vector register.
pub const V_MUL_U32_U24: u16 = 267;
/// Multiply two unsigned 24-bit integer inputs and store the high 32 bits of the result as an unsigned 32-bit integer in...
pub const V_MUL_HI_U32_U24: u16 = 268;
/// Select the minimum of two single-precision float inputs and store the result into a vector register.
pub const V_MIN_F32: u16 = 271;
/// Select the maximum of two single-precision float inputs and store the result into a vector register.
pub const V_MAX_F32: u16 = 272;
/// Select the minimum of two signed 32-bit integer inputs and store the selected value into a vector register.
pub const V_MIN_I32: u16 = 273;
/// Select the maximum of two signed 32-bit integer inputs and store the selected value into a vector register.
pub const V_MAX_I32: u16 = 274;
/// Select the minimum of two unsigned 32-bit integer inputs and store the selected value into a vector register.
pub const V_MIN_U32: u16 = 275;
/// Select the maximum of two unsigned 32-bit integer inputs and store the selected value into a vector register.
pub const V_MAX_U32: u16 = 276;
/// Given a shift count in the first vector input, calculate the logical shift right of the second vector input and store...
pub const V_LSHRREV_B32: u16 = 278;
/// Given a shift count in the first vector input, calculate the arithmetic shift right (preserving sign bit) of the seco...
pub const V_ASHRREV_I32: u16 = 280;
/// Given a shift count in the first vector input, calculate the logical shift left of the second vector input and store ...
pub const V_LSHLREV_B32: u16 = 282;
/// Calculate bitwise AND on two vector inputs and store the result into a vector register.
pub const V_AND_B32: u16 = 283;
/// Calculate bitwise OR on two vector inputs and store the result into a vector register.
pub const V_OR_B32: u16 = 284;
/// Calculate bitwise XOR on two vector inputs and store the result into a vector register.
pub const V_XOR_B32: u16 = 285;
/// Calculate bitwise XNOR on two vector inputs and store the result into a vector register.
pub const V_XNOR_B32: u16 = 286;
/// Add two unsigned 32-bit integer inputs and store the result into a vector register. No carry-in or carry-out support.
pub const V_ADD_NC_U32: u16 = 293;
/// Subtract the second unsigned input from the first input and store the result into a vector register. No carry-in or c...
pub const V_SUB_NC_U32: u16 = 294;
/// Subtract the first unsigned input from the second input and store the result into a vector register. No carry-in or c...
pub const V_SUBREV_NC_U32: u16 = 295;
/// Multiply two floating point inputs and accumulate the result into the destination register using fused multiply add.
pub const V_FMAC_F32: u16 = 299;
/// Convert two single-precision float inputs to a packed half-precision float value using round toward zero semantics (i...
pub const V_CVT_PKRTZ_F16_F32: u16 = 303;
/// Add two floating point inputs and store the result into a vector register.
pub const V_ADD_F16: u16 = 306;
/// Subtract the second floating point input from the first input and store the result into a vector register.
pub const V_SUB_F16: u16 = 307;
/// Subtract the first floating point input from the second input and store the result into a vector register.
pub const V_SUBREV_F16: u16 = 308;
/// Multiply two floating point inputs and store the result into a vector register.
pub const V_MUL_F16: u16 = 309;
/// Multiply two floating point inputs and accumulate the result into the destination register using fused multiply add.
pub const V_FMAC_F16: u16 = 310;
/// Select the maximum of two half-precision float inputs and store the result into a vector register.
pub const V_MAX_F16: u16 = 313;
/// Select the minimum of two half-precision float inputs and store the result into a vector register.
pub const V_MIN_F16: u16 = 314;
/// Multiply the first input, a floating point value, by an integral power of 2 specified in the second input, a signed i...
pub const V_LDEXP_F16: u16 = 315;
/// Multiply and add single-precision values. Follows DX9 rules where 0.0 times anything produces 0.0.
pub const V_FMA_LEGACY_F32: u16 = 320;
/// Multiply two signed 24-bit integer inputs in the signed 32-bit integer domain, add a signed 32-bit integer value from...
pub const V_MAD_I32_I24: u16 = 322;
/// Multiply two unsigned 24-bit integer inputs in the unsigned 32-bit integer domain, add a unsigned 32-bit integer valu...
pub const V_MAD_U32_U24: u16 = 323;
/// Compute the cubemap face ID of a 3D coordinate specified as three single-precision float inputs. Store the result in ...
pub const V_CUBEID_F32: u16 = 324;
/// Compute the cubemap S coordinate of a 3D coordinate specified as three single-precision float inputs. Store the resul...
pub const V_CUBESC_F32: u16 = 325;
/// Compute the cubemap T coordinate of a 3D coordinate specified as three single-precision float inputs. Store the resul...
pub const V_CUBETC_F32: u16 = 326;
/// Compute the cubemap major axis coordinate of a 3D coordinate specified as three single-precision float inputs. Store ...
pub const V_CUBEMA_F32: u16 = 327;
/// Extract an unsigned bitfield from the first input using field offset from the second input and size from the third in...
pub const V_BFE_U32: u16 = 328;
/// Extract a signed bitfield from the first input using field offset from the second input and size from the third input...
pub const V_BFE_I32: u16 = 329;
/// Overwrite a bitfield in the third input with a bitfield from the second input using a mask from the first input, then...
pub const V_BFI_B32: u16 = 330;
/// Multiply two single-precision float inputs and add a third input using fused multiply add, and store the result into ...
pub const V_FMA_F32: u16 = 331;
/// Multiply two double-precision float inputs and add a third input using fused multiply add, and store the result into ...
pub const V_FMA_F64: u16 = 332;
/// Average two 4-D vectors stored as packed bytes in the first two inputs with rounding control provided by the third in...
pub const V_LERP_U8: u16 = 333;
/// Align a 64-bit value encoded in the first two inputs to a bit position specified in the third input, then store the r...
pub const V_ALIGNBIT_B32: u16 = 334;
/// Align a 64-bit value encoded in the first two inputs to a byte position specified in the third input, then store the ...
pub const V_ALIGNBYTE_B32: u16 = 335;
/// Multiply two floating point inputs and store the result into a vector register. Specific rules apply to accommodate l...
pub const V_MULLIT_F32: u16 = 336;
/// Select the minimum of three single-precision float inputs and store the selected value into a vector register.
pub const V_MIN3_F32: u16 = 337;
/// Select the minimum of three signed 32-bit integer inputs and store the selected value into a vector register.
pub const V_MIN3_I32: u16 = 338;
/// Select the minimum of three unsigned 32-bit integer inputs and store the selected value into a vector register.
pub const V_MIN3_U32: u16 = 339;
/// Select the maximum of three single-precision float inputs and store the selected value into a vector register.
pub const V_MAX3_F32: u16 = 340;
/// Select the maximum of three signed 32-bit integer inputs and store the selected value into a vector register.
pub const V_MAX3_I32: u16 = 341;
/// Select the maximum of three unsigned 32-bit integer inputs and store the selected value into a vector register.
pub const V_MAX3_U32: u16 = 342;
/// Select the median of three single-precision float values and store the selected value into a vector register.
pub const V_MED3_F32: u16 = 343;
/// Select the median of three signed 32-bit integer values and store the selected value into a vector register.
pub const V_MED3_I32: u16 = 344;
/// Select the median of three unsigned 32-bit integer values and store the selected value into a vector register.
pub const V_MED3_U32: u16 = 345;
/// Calculate the sum of absolute differences of elements in two packed 4-component unsigned 8-bit integer inputs, add an...
pub const V_SAD_U8: u16 = 346;
/// Calculate the sum of absolute differences of elements in two packed 4-component unsigned 8-bit integer inputs, shift ...
pub const V_SAD_HI_U8: u16 = 347;
/// Calculate the sum of absolute differences of elements in two packed 2-component unsigned 16-bit integer inputs, add a...
pub const V_SAD_U16: u16 = 348;
/// Calculate the absolute difference of two unsigned 32-bit integer inputs, add an unsigned 32-bit integer value from th...
pub const V_SAD_U32: u16 = 349;
/// Convert a single-precision float value from the first input to an unsigned 8-bit integer value and pack the result in...
pub const V_CVT_PK_U8_F32: u16 = 350;
/// Given a single-precision float quotient in the first input, a denominator in the second input and a numerator in the ...
pub const V_DIV_FIXUP_F32: u16 = 351;
/// Given a double-precision float quotient in the first input, a denominator in the second input and a numerator in the ...
pub const V_DIV_FIXUP_F64: u16 = 352;
/// Add two floating point inputs and store the result into a vector register.
pub const V_ADD_F64: u16 = 356;
/// Multiply two floating point inputs and store the result into a vector register.
pub const V_MUL_F64: u16 = 357;
/// Select the minimum of two double-precision float inputs and store the result into a vector register.
pub const V_MIN_F64: u16 = 358;
/// Select the maximum of two double-precision float inputs and store the result into a vector register.
pub const V_MAX_F64: u16 = 359;
/// Multiply the first input, a floating point value, by an integral power of 2 specified in the second input, a signed i...
pub const V_LDEXP_F64: u16 = 360;
/// Multiply two unsigned 32-bit integer inputs and store the result into a vector register.
pub const V_MUL_LO_U32: u16 = 361;
/// Multiply two unsigned 32-bit integer inputs and store the high 32 bits of the result into a vector register.
pub const V_MUL_HI_U32: u16 = 362;
/// Multiply two signed 32-bit integer inputs and store the high 32 bits of the result into a vector register.
pub const V_MUL_HI_I32: u16 = 364;
/// Multiply two single-precision float inputs and add a third input using fused multiply add, then scale the exponent of...
pub const V_DIV_FMAS_F32: u16 = 367;
/// Multiply two double-precision float inputs and add a third input using fused multiply add, then scale the exponent of...
pub const V_DIV_FMAS_F64: u16 = 368;
/// Calculate the sum of absolute differences of elements in two packed 4-component unsigned 8-bit integer inputs, except...
pub const V_MSAD_U8: u16 = 369;
/// Perform the V_SAD_U8 operation four times using different slices of the first array, all entries of the second array ...
pub const V_QSAD_PK_U16_U8: u16 = 370;
/// Perform the V_MSAD_U8 operation four times using different slices of the first array, all entries of the second array...
pub const V_MQSAD_PK_U16_U8: u16 = 371;
/// Look up a 53-bit segment of 2/PI using an integer segment select in the second input. Scale the intermediate result b...
pub const V_TRIG_PREOP_F64: u16 = 372;
/// Perform the V_MSAD_U8 operation four times using different slices of the first array, all entries of the second array...
pub const V_MQSAD_U32_U8: u16 = 373;
/// Calculate the bitwise XOR of three vector inputs and store the result into a vector register.
pub const V_XOR3_B32: u16 = 376;
/// Do nothing.
pub const V_NOP: u16 = 384;
/// Move data from a vector input into a vector register.
pub const V_MOV_B32: u16 = 385;
/// Read the scalar value in the lowest active lane of the input vector register and store it into a scalar register.
pub const V_READFIRSTLANE_B32: u16 = 386;
/// Convert from a double-precision float input to a signed 32-bit integer value and store the result into a vector regis...
pub const V_CVT_I32_F64: u16 = 387;
/// Convert from a signed 32-bit integer input to a double-precision float value and store the result into a vector regis...
pub const V_CVT_F64_I32: u16 = 388;
/// Convert from a signed 32-bit integer input to a single-precision float value and store the result into a vector regis...
pub const V_CVT_F32_I32: u16 = 389;
/// Convert from an unsigned 32-bit integer input to a single-precision float value and store the result into a vector re...
pub const V_CVT_F32_U32: u16 = 390;
/// Convert from a single-precision float input to an unsigned 32-bit integer value and store the result into a vector re...
pub const V_CVT_U32_F32: u16 = 391;
/// Convert from a single-precision float input to a signed 32-bit integer value and store the result into a vector regis...
pub const V_CVT_I32_F32: u16 = 392;
/// Convert from a single-precision float input to a half-precision float value and store the result into a vector register.
pub const V_CVT_F16_F32: u16 = 394;
/// Convert from a half-precision float input to a single-precision float value and store the result into a vector register.
pub const V_CVT_F32_F16: u16 = 395;
/// Convert from a single-precision float input to a signed 32-bit integer value using round to nearest integer semantics...
pub const V_CVT_RPI_I32_F32: u16 = 396;
/// Convert from a single-precision float input to a signed 32-bit integer value using round-down semantics (ignore the d...
pub const V_CVT_FLR_I32_F32: u16 = 397;
/// Convert from a signed 4-bit integer input to a single-precision float value using an offset table and store the resul...
pub const V_CVT_OFF_F32_I4: u16 = 398;
/// Convert from a double-precision float input to a single-precision float value and store the result into a vector regi...
pub const V_CVT_F32_F64: u16 = 399;
/// Convert from a single-precision float input to a double-precision float value and store the result into a vector regi...
pub const V_CVT_F64_F32: u16 = 400;
/// Convert an unsigned byte in byte 0 of the input to a single-precision float value and store the result into a vector ...
pub const V_CVT_F32_UBYTE0: u16 = 401;
/// Convert an unsigned byte in byte 1 of the input to a single-precision float value and store the result into a vector ...
pub const V_CVT_F32_UBYTE1: u16 = 402;
/// Convert an unsigned byte in byte 2 of the input to a single-precision float value and store the result into a vector ...
pub const V_CVT_F32_UBYTE2: u16 = 403;
/// Convert an unsigned byte in byte 3 of the input to a single-precision float value and store the result into a vector ...
pub const V_CVT_F32_UBYTE3: u16 = 404;
/// Convert from a double-precision float input to an unsigned 32-bit integer value and store the result into a vector re...
pub const V_CVT_U32_F64: u16 = 405;
/// Convert from an unsigned 32-bit integer input to a double-precision float value and store the result into a vector re...
pub const V_CVT_F64_U32: u16 = 406;
/// Compute the integer part of a double-precision float input using round toward zero semantics and store the result in ...
pub const V_TRUNC_F64: u16 = 407;
/// Round the double-precision float input up to next integer and store the result in floating point format into a vector...
pub const V_CEIL_F64: u16 = 408;
/// Round the double-precision float input to the nearest even integer and store the result in floating point format into...
pub const V_RNDNE_F64: u16 = 409;
/// Round the double-precision float input down to previous integer and store the result in floating point format into a ...
pub const V_FLOOR_F64: u16 = 410;
/// Flush the vector ALU pipeline through the destination cache.
pub const V_PIPEFLUSH: u16 = 411;
/// Compute the fractional portion of a single-precision float input and store the result in floating point format into a...
pub const V_FRACT_F32: u16 = 416;
/// Compute the integer part of a single-precision float input using round toward zero semantics and store the result in ...
pub const V_TRUNC_F32: u16 = 417;
/// Round the single-precision float input up to next integer and store the result in floating point format into a vector...
pub const V_CEIL_F32: u16 = 418;
/// Round the single-precision float input to the nearest even integer and store the result in floating point format into...
pub const V_RNDNE_F32: u16 = 419;
/// Round the single-precision float input down to previous integer and store the result in floating point format into a ...
pub const V_FLOOR_F32: u16 = 420;
/// Calculate 2 raised to the power of the single-precision float input and store the result into a vector register.
pub const V_EXP_F32: u16 = 421;
/// Calculate the base 2 logarithm of the single-precision float input and store the result into a vector register.
pub const V_LOG_F32: u16 = 423;
/// Calculate the reciprocal of the single-precision float input using IEEE rules and store the result into a vector regi...
pub const V_RCP_F32: u16 = 426;
/// Calculate the reciprocal of the vector float input in a manner suitable for integer division and store the result int...
pub const V_RCP_IFLAG_F32: u16 = 427;
/// Calculate the reciprocal of the square root of the single-precision float input using IEEE rules and store the result...
pub const V_RSQ_F32: u16 = 430;
/// Calculate the reciprocal of the double-precision float input using IEEE rules and store the result into a vector regi...
pub const V_RCP_F64: u16 = 431;
/// Calculate the reciprocal of the square root of the double-precision float input using IEEE rules and store the result...
pub const V_RSQ_F64: u16 = 433;
/// Calculate the square root of the single-precision float input using IEEE rules and store the result into a vector reg...
pub const V_SQRT_F32: u16 = 435;
/// Calculate the square root of the double-precision float input using IEEE rules and store the result into a vector reg...
pub const V_SQRT_F64: u16 = 436;
/// Calculate the trigonometric sine of a single-precision float value using IEEE rules and store the result into a vecto...
pub const V_SIN_F32: u16 = 437;
/// Calculate the trigonometric cosine of a single-precision float value using IEEE rules and store the result into a vec...
pub const V_COS_F32: u16 = 438;
/// Calculate bitwise negation on a vector input and store the result into a vector register.
pub const V_NOT_B32: u16 = 439;
/// Reverse the order of bits in a vector input and store the result into a vector register.
pub const V_BFREV_B32: u16 = 440;
/// Count the number of leading \"0\" bits before the first \"1\" in a vector input and store the result into a vector re...
pub const V_FFBH_U32: u16 = 441;
/// Count the number of trailing \"0\" bits before the first \"1\" in a vector input and store the result into a vector r...
pub const V_FFBL_B32: u16 = 442;
/// Count the number of leading bits that are the same as the sign bit of a vector input and store the result into a vect...
pub const V_FFBH_I32: u16 = 443;
/// Extract the exponent of a double-precision float input and store the result as a signed 32-bit integer into a vector ...
pub const V_FREXP_EXP_I32_F64: u16 = 444;
/// Extract the binary significand, or mantissa, of a double-precision float input and store the result as a double-preci...
pub const V_FREXP_MANT_F64: u16 = 445;
/// Compute the fractional portion of a double-precision float input and store the result in floating point format into a...
pub const V_FRACT_F64: u16 = 446;
/// Extract the exponent of a single-precision float input and store the result as a signed 32-bit integer into a vector ...
pub const V_FREXP_EXP_I32_F32: u16 = 447;
/// Extract the binary significand, or mantissa, of a single-precision float input and store the result as a single-preci...
pub const V_FREXP_MANT_F32: u16 = 448;
/// Clear this wave's exception state in the vector ALU.
pub const V_CLREXCP: u16 = 449;
/// Move data from a vector input into a relatively-indexed vector register.
pub const V_MOVRELD_B32: u16 = 450;
/// Move data from a relatively-indexed vector register into another vector register.
pub const V_MOVRELS_B32: u16 = 451;
/// Move data from a relatively-indexed vector register into another relatively-indexed vector register.
pub const V_MOVRELSD_B32: u16 = 452;
/// Move data from a relatively-indexed vector register into another relatively-indexed vector register, using different ...
pub const V_MOVRELSD_2_B32: u16 = 456;
/// Convert from an unsigned 16-bit integer input to a half-precision float value and store the result into a vector regi...
pub const V_CVT_F16_U16: u16 = 464;
/// Convert from a signed 16-bit integer input to a half-precision float value and store the result into a vector register.
pub const V_CVT_F16_I16: u16 = 465;
/// Convert from a half-precision float input to an unsigned 16-bit integer value and store the result into a vector regi...
pub const V_CVT_U16_F16: u16 = 466;
/// Convert from a half-precision float input to a signed 16-bit integer value and store the result into a vector register.
pub const V_CVT_I16_F16: u16 = 467;
/// Calculate the reciprocal of the half-precision float input using IEEE rules and store the result into a vector register.
pub const V_RCP_F16: u16 = 468;
/// Calculate the square root of the half-precision float input using IEEE rules and store the result into a vector regis...
pub const V_SQRT_F16: u16 = 469;
/// Calculate the reciprocal of the square root of the half-precision float input using IEEE rules and store the result i...
pub const V_RSQ_F16: u16 = 470;
/// Calculate the base 2 logarithm of the half-precision float input and store the result into a vector register.
pub const V_LOG_F16: u16 = 471;
/// Calculate 2 raised to the power of the half-precision float input and store the result into a vector register.
pub const V_EXP_F16: u16 = 472;
/// Extract the binary significand, or mantissa, of a half-precision float input and store the result as a half-precision...
pub const V_FREXP_MANT_F16: u16 = 473;
/// Extract the exponent of a half-precision float input and store the result as a signed 16-bit integer into a vector re...
pub const V_FREXP_EXP_I16_F16: u16 = 474;
/// Round the half-precision float input down to previous integer and store the result in floating point format into a ve...
pub const V_FLOOR_F16: u16 = 475;
/// Round the half-precision float input up to next integer and store the result in floating point format into a vector r...
pub const V_CEIL_F16: u16 = 476;
/// Compute the integer part of a half-precision float input using round toward zero semantics and store the result in fl...
pub const V_TRUNC_F16: u16 = 477;
/// Round the half-precision float input to the nearest even integer and store the result in floating point format into a...
pub const V_RNDNE_F16: u16 = 478;
/// Compute the fractional portion of a half-precision float input and store the result in floating point format into a v...
pub const V_FRACT_F16: u16 = 479;
/// Calculate the trigonometric sine of a half-precision float value using IEEE rules and store the result into a vector ...
pub const V_SIN_F16: u16 = 480;
/// Calculate the trigonometric cosine of a half-precision float value using IEEE rules and store the result into a vecto...
pub const V_COS_F16: u16 = 481;
/// Given two 16-bit unsigned integer inputs, saturate each input over an 8-bit unsigned range, pack the resulting values...
pub const V_SAT_PK_U8_I16: u16 = 482;
/// Convert from a half-precision float input to a signed normalized short and store the result into a vector register.
pub const V_CVT_NORM_I16_F16: u16 = 483;
/// Convert from a half-precision float input to an unsigned normalized short and store the result into a vector register.
pub const V_CVT_NORM_U16_F16: u16 = 484;
/// Given the I coordinate in a vector register and an attribute specifier, load parameter data from the local data share...
pub const V_INTERP_P1_F32: u16 = 512;
/// Given the J coordinate in a vector register, an attribute specifier and the result of a prior V_INTERP_P1_F32 in the ...
pub const V_INTERP_P2_F32: u16 = 513;
/// Given an attribute specifier and a parameter ID (P0, P10 or P20), load one of the parameter values from the local dat...
pub const V_INTERP_MOV_F32: u16 = 514;
/// Given a shift count in the first vector input, calculate the logical shift left of the second vector input and store ...
pub const V_LSHLREV_B64: u16 = 767;
/// Given a shift count in the first vector input, calculate the logical shift right of the second vector input and store...
pub const V_LSHRREV_B64: u16 = 768;
/// Given a shift count in the first vector input, calculate the arithmetic shift right (preserving sign bit) of the seco...
pub const V_ASHRREV_I64: u16 = 769;
/// Add two unsigned 16-bit integer inputs and store the result into a vector register. No carry-in or carry-out support.
pub const V_ADD_NC_U16: u16 = 771;
/// Subtract the second unsigned input from the first input and store the result into a vector register. No carry-in or c...
pub const V_SUB_NC_U16: u16 = 772;
/// Multiply two unsigned 16-bit integer inputs and store the low bits of the result into a vector register.
pub const V_MUL_LO_U16: u16 = 773;
/// Given a shift count in the first vector input, calculate the logical shift right of the second vector input and store...
pub const V_LSHRREV_B16: u16 = 775;
/// Given a shift count in the first vector input, calculate the arithmetic shift right (preserving sign bit) of the seco...
pub const V_ASHRREV_I16: u16 = 776;
/// Select the maximum of two unsigned 16-bit integer inputs and store the selected value into a vector register.
pub const V_MAX_U16: u16 = 777;
/// Select the maximum of two signed 16-bit integer inputs and store the selected value into a vector register.
pub const V_MAX_I16: u16 = 778;
/// Select the minimum of two unsigned 16-bit integer inputs and store the selected value into a vector register.
pub const V_MIN_U16: u16 = 779;
/// Select the minimum of two signed 16-bit integer inputs and store the selected value into a vector register.
pub const V_MIN_I16: u16 = 780;
/// Add two signed 16-bit integer inputs and store the result into a vector register. No carry-in or carry-out support.
pub const V_ADD_NC_I16: u16 = 781;
/// Subtract the second signed input from the first input and store the result into a vector register. No carry-in or car...
pub const V_SUB_NC_I16: u16 = 782;
/// Pack two half-precision float values into a single 32-bit value and store the result into a vector register.
pub const V_PACK_B32_F16: u16 = 785;
/// Convert from two half-precision float inputs to a packed signed normalized short and store the result into a vector r...
pub const V_CVT_PKNORM_I16_F16: u16 = 786;
/// Convert from two half-precision float inputs to a packed unsigned normalized short and store the result into a vector...
pub const V_CVT_PKNORM_U16_F16: u16 = 787;
/// Given a shift count in the first vector input, calculate the logical shift left of the second vector input and store ...
pub const V_LSHLREV_B16: u16 = 788;
/// Multiply two unsigned 16-bit integer inputs, add an unsigned 16-bit integer value from a third input, and store the r...
pub const V_MAD_U16: u16 = 832;
/// Given a single-precision float I coordinate in a vector register and an attribute specifier, load two half-precision ...
pub const V_INTERP_P1LL_F16: u16 = 834;
/// Given a single-precision float I coordinate in a vector register, a half-precision float P0 value in another vector r...
pub const V_INTERP_P1LV_F16: u16 = 835;
/// Permute a 64-bit value constructed from two vector inputs (most significant bits come from the first input) using a p...
pub const V_PERM_B32: u16 = 836;
/// Calculate bitwise XOR of the first two vector inputs, then add the third vector input to the intermediate result, the...
pub const V_XAD_U32: u16 = 837;
/// Given a shift count in the second input, calculate the logical shift left of the first input, then add the third inpu...
pub const V_LSHL_ADD_U32: u16 = 838;
/// Add the first two integer inputs, then given a shift count in the third input, calculate the logical shift left of th...
pub const V_ADD_LSHL_U32: u16 = 839;
/// Multiply two half-precision float inputs and add a third input using fused multiply add, and store the result into a ...
pub const V_FMA_F16: u16 = 843;
/// Select the minimum of three half-precision float inputs and store the selected value into a vector register.
pub const V_MIN3_F16: u16 = 849;
/// Select the minimum of three signed 16-bit integer inputs and store the selected value into a vector register.
pub const V_MIN3_I16: u16 = 850;
/// Select the minimum of three unsigned 16-bit integer inputs and store the selected value into a vector register.
pub const V_MIN3_U16: u16 = 851;
/// Select the maximum of three half-precision float inputs and store the selected value into a vector register.
pub const V_MAX3_F16: u16 = 852;
/// Select the maximum of three signed 16-bit integer inputs and store the selected value into a vector register.
pub const V_MAX3_I16: u16 = 853;
/// Select the maximum of three unsigned 16-bit integer inputs and store the selected value into a vector register.
pub const V_MAX3_U16: u16 = 854;
/// Select the median of three half-precision float values and store the selected value into a vector register.
pub const V_MED3_F16: u16 = 855;
/// Select the median of three signed 16-bit integer values and store the selected value into a vector register.
pub const V_MED3_I16: u16 = 856;
/// Select the median of three unsigned 16-bit integer values and store the selected value into a vector register.
pub const V_MED3_U16: u16 = 857;
/// Given a single-precision float J coordinate in a vector register, an attribute specifier and the result of a prior V_...
pub const V_INTERP_P2_F16: u16 = 858;
/// Multiply two signed 16-bit integer inputs, add a signed 16-bit integer value from a third input, and store the result...
pub const V_MAD_I16: u16 = 862;
/// Given a half-precision float quotient in the first input, a denominator in the second input and a numerator in the th...
pub const V_DIV_FIXUP_F16: u16 = 863;
/// Read the scalar value in the specified lane of the first input where the lane select is in the second input. Store th...
pub const V_READLANE_B32: u16 = 864;
/// Write the scalar value in the first input into the specified lane of a vector register where the lane select is in th...
pub const V_WRITELANE_B32: u16 = 865;
/// Multiply the first input, a floating point value, by an integral power of 2 specified in the second input, a signed i...
pub const V_LDEXP_F32: u16 = 866;
/// Calculate a bitfield mask given a field offset and size and store the result into a vector register.
pub const V_BFM_B32: u16 = 867;
/// Count the number of \"1\" bits in the vector input and store the result into a vector register.
pub const V_BCNT_U32_B32: u16 = 868;
/// For each lane 0
pub const V_MBCNT_LO_U32_B32: u16 = 869;
/// For each lane 32
pub const V_MBCNT_HI_U32_B32: u16 = 870;
/// Convert from two single-precision float inputs to a packed signed normalized short and store the result into a vector...
pub const V_CVT_PKNORM_I16_F32: u16 = 872;
/// Convert from two single-precision float inputs to a packed unsigned normalized short and store the result into a vect...
pub const V_CVT_PKNORM_U16_F32: u16 = 873;
/// Convert from two unsigned 32-bit integer inputs to a packed unsigned 16-bit integer value and store the result into a...
pub const V_CVT_PK_U16_U32: u16 = 874;
/// Convert from two signed 32-bit integer inputs to a packed signed 16-bit integer value and store the result into a vec...
pub const V_CVT_PK_I16_I32: u16 = 875;
/// Add three unsigned inputs and store the result into a vector register. No carry-in or carry-out support.
pub const V_ADD3_U32: u16 = 877;
/// Given a shift count in the second input, calculate the logical shift left of the first input, then calculate the bitw...
pub const V_LSHL_OR_B32: u16 = 879;
/// Calculate bitwise AND on the first two vector inputs, then compute the bitwise OR of the intermediate result and the ...
pub const V_AND_OR_B32: u16 = 881;
/// Calculate the bitwise OR of three vector inputs and store the result into a vector register.
pub const V_OR3_B32: u16 = 882;
/// Multiply two unsigned 16-bit integer inputs in the unsigned 32-bit integer domain, add an unsigned 32-bit integer val...
pub const V_MAD_U32_U16: u16 = 883;
/// Multiply two signed 16-bit integer inputs in the signed 32-bit integer domain, add a signed 32-bit integer value from...
pub const V_MAD_I32_I16: u16 = 885;
/// Subtract the second signed input from the first input and store the result into a vector register. No carry-in or car...
pub const V_SUB_NC_I32: u16 = 886;
/// Perform arbitrary gather-style operation within a row (16 contiguous lanes).
pub const V_PERMLANE16_B32: u16 = 887;
/// Perform arbitrary gather-style operation across two rows (each row is 16 contiguous lanes).
pub const V_PERMLANEX16_B32: u16 = 888;
/// Add two signed 32-bit integer inputs and store the result into a vector register. No carry-in or carry-out support.
pub const V_ADD_NC_I32: u16 = 895;
