// SPDX-License-Identifier: AGPL-3.0-only
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::super::isa_types::InstrEntry;

/// All ENC_VOP3 instructions.
pub const TABLE: &[InstrEntry] = &[
    InstrEntry {
        name: "V_CMP_F_F32",
        opcode: 0,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_F32",
        opcode: 1,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_F32",
        opcode: 2,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_F32",
        opcode: 3,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_F32",
        opcode: 4,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LG_F32",
        opcode: 5,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_F32",
        opcode: 6,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_O_F32",
        opcode: 7,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_U_F32",
        opcode: 8,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGE_F32",
        opcode: 9,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLG_F32",
        opcode: 10,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGT_F32",
        opcode: 11,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLE_F32",
        opcode: 12,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NEQ_F32",
        opcode: 13,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLT_F32",
        opcode: 14,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_TRU_F32",
        opcode: 15,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_F32",
        opcode: 16,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_F32",
        opcode: 17,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_F32",
        opcode: 18,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_F32",
        opcode: 19,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_F32",
        opcode: 20,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LG_F32",
        opcode: 21,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_F32",
        opcode: 22,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_O_F32",
        opcode: 23,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_U_F32",
        opcode: 24,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGE_F32",
        opcode: 25,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLG_F32",
        opcode: 26,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGT_F32",
        opcode: 27,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLE_F32",
        opcode: 28,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NEQ_F32",
        opcode: 29,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLT_F32",
        opcode: 30,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_TRU_F32",
        opcode: 31,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_F64",
        opcode: 32,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_F64",
        opcode: 33,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_F64",
        opcode: 34,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_F64",
        opcode: 35,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_F64",
        opcode: 36,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LG_F64",
        opcode: 37,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_F64",
        opcode: 38,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_O_F64",
        opcode: 39,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_U_F64",
        opcode: 40,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGE_F64",
        opcode: 41,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLG_F64",
        opcode: 42,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGT_F64",
        opcode: 43,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLE_F64",
        opcode: 44,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NEQ_F64",
        opcode: 45,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLT_F64",
        opcode: 46,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_TRU_F64",
        opcode: 47,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_F64",
        opcode: 48,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_F64",
        opcode: 49,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_F64",
        opcode: 50,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_F64",
        opcode: 51,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_F64",
        opcode: 52,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LG_F64",
        opcode: 53,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_F64",
        opcode: 54,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_O_F64",
        opcode: 55,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_U_F64",
        opcode: 56,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGE_F64",
        opcode: 57,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLG_F64",
        opcode: 58,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGT_F64",
        opcode: 59,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLE_F64",
        opcode: 60,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NEQ_F64",
        opcode: 61,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLT_F64",
        opcode: 62,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_TRU_F64",
        opcode: 63,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_I32",
        opcode: 128,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_I32",
        opcode: 129,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_I32",
        opcode: 130,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_I32",
        opcode: 131,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_I32",
        opcode: 132,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_I32",
        opcode: 133,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_I32",
        opcode: 134,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_I32",
        opcode: 135,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_CLASS_F32",
        opcode: 136,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_I16",
        opcode: 137,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_I16",
        opcode: 138,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_I16",
        opcode: 139,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_I16",
        opcode: 140,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_I16",
        opcode: 141,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_I16",
        opcode: 142,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_CLASS_F16",
        opcode: 143,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_I32",
        opcode: 144,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_I32",
        opcode: 145,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_I32",
        opcode: 146,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_I32",
        opcode: 147,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_I32",
        opcode: 148,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_I32",
        opcode: 149,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_I32",
        opcode: 150,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_I32",
        opcode: 151,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_CLASS_F32",
        opcode: 152,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_I16",
        opcode: 153,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_I16",
        opcode: 154,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_I16",
        opcode: 155,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_I16",
        opcode: 156,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_I16",
        opcode: 157,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_I16",
        opcode: 158,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_CLASS_F16",
        opcode: 159,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_I64",
        opcode: 160,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_I64",
        opcode: 161,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_I64",
        opcode: 162,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_I64",
        opcode: 163,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_I64",
        opcode: 164,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_I64",
        opcode: 165,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_I64",
        opcode: 166,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_I64",
        opcode: 167,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_CLASS_F64",
        opcode: 168,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_U16",
        opcode: 169,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_U16",
        opcode: 170,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_U16",
        opcode: 171,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_U16",
        opcode: 172,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_U16",
        opcode: 173,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_U16",
        opcode: 174,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_I64",
        opcode: 176,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_I64",
        opcode: 177,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_I64",
        opcode: 178,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_I64",
        opcode: 179,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_I64",
        opcode: 180,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_I64",
        opcode: 181,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_I64",
        opcode: 182,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_I64",
        opcode: 183,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_CLASS_F64",
        opcode: 184,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_U16",
        opcode: 185,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_U16",
        opcode: 186,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_U16",
        opcode: 187,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_U16",
        opcode: 188,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_U16",
        opcode: 189,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_U16",
        opcode: 190,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_U32",
        opcode: 192,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_U32",
        opcode: 193,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_U32",
        opcode: 194,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_U32",
        opcode: 195,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_U32",
        opcode: 196,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_U32",
        opcode: 197,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_U32",
        opcode: 198,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_U32",
        opcode: 199,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_F16",
        opcode: 200,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_F16",
        opcode: 201,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_F16",
        opcode: 202,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_F16",
        opcode: 203,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_F16",
        opcode: 204,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LG_F16",
        opcode: 205,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_F16",
        opcode: 206,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_O_F16",
        opcode: 207,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_U32",
        opcode: 208,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_U32",
        opcode: 209,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_U32",
        opcode: 210,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_U32",
        opcode: 211,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_U32",
        opcode: 212,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_U32",
        opcode: 213,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_U32",
        opcode: 214,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_U32",
        opcode: 215,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_F16",
        opcode: 216,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_F16",
        opcode: 217,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_F16",
        opcode: 218,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_F16",
        opcode: 219,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_F16",
        opcode: 220,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LG_F16",
        opcode: 221,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_F16",
        opcode: 222,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_O_F16",
        opcode: 223,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_U64",
        opcode: 224,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_U64",
        opcode: 225,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_U64",
        opcode: 226,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_U64",
        opcode: 227,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_U64",
        opcode: 228,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_U64",
        opcode: 229,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_U64",
        opcode: 230,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_U64",
        opcode: 231,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_U_F16",
        opcode: 232,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGE_F16",
        opcode: 233,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLG_F16",
        opcode: 234,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGT_F16",
        opcode: 235,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLE_F16",
        opcode: 236,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NEQ_F16",
        opcode: 237,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLT_F16",
        opcode: 238,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_TRU_F16",
        opcode: 239,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_U64",
        opcode: 240,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_U64",
        opcode: 241,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_U64",
        opcode: 242,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_U64",
        opcode: 243,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_U64",
        opcode: 244,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_U64",
        opcode: 245,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_U64",
        opcode: 246,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_U64",
        opcode: 247,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_U_F16",
        opcode: 248,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGE_F16",
        opcode: 249,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLG_F16",
        opcode: 250,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGT_F16",
        opcode: 251,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLE_F16",
        opcode: 252,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NEQ_F16",
        opcode: 253,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLT_F16",
        opcode: 254,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_TRU_F16",
        opcode: 255,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CNDMASK_B32",
        opcode: 257,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_F32",
        opcode: 259,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_F32",
        opcode: 260,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUBREV_F32",
        opcode: 261,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMAC_LEGACY_F32",
        opcode: 262,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_LEGACY_F32",
        opcode: 263,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_F32",
        opcode: 264,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_I32_I24",
        opcode: 265,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_I32_I24",
        opcode: 266,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_U32_U24",
        opcode: 267,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_U32_U24",
        opcode: 268,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_F32",
        opcode: 271,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_F32",
        opcode: 272,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_I32",
        opcode: 273,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_I32",
        opcode: 274,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_U32",
        opcode: 275,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_U32",
        opcode: 276,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHRREV_B32",
        opcode: 278,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ASHRREV_I32",
        opcode: 280,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHLREV_B32",
        opcode: 282,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_AND_B32",
        opcode: 283,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_OR_B32",
        opcode: 284,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_XOR_B32",
        opcode: 285,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_XNOR_B32",
        opcode: 286,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_U32",
        opcode: 293,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_U32",
        opcode: 294,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUBREV_NC_U32",
        opcode: 295,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMAC_F32",
        opcode: 299,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PKRTZ_F16_F32",
        opcode: 303,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_F16",
        opcode: 306,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_F16",
        opcode: 307,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUBREV_F16",
        opcode: 308,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_F16",
        opcode: 309,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMAC_F16",
        opcode: 310,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_F16",
        opcode: 313,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_F16",
        opcode: 314,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LDEXP_F16",
        opcode: 315,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_LEGACY_F32",
        opcode: 320,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_I32_I24",
        opcode: 322,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_U32_U24",
        opcode: 323,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBEID_F32",
        opcode: 324,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBESC_F32",
        opcode: 325,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBETC_F32",
        opcode: 326,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBEMA_F32",
        opcode: 327,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_BFE_U32",
        opcode: 328,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_BFE_I32",
        opcode: 329,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_BFI_B32",
        opcode: 330,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_F32",
        opcode: 331,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_F64",
        opcode: 332,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LERP_U8",
        opcode: 333,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ALIGNBIT_B32",
        opcode: 334,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ALIGNBYTE_B32",
        opcode: 335,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MULLIT_F32",
        opcode: 336,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_F32",
        opcode: 337,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_I32",
        opcode: 338,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_U32",
        opcode: 339,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_F32",
        opcode: 340,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_I32",
        opcode: 341,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_U32",
        opcode: 342,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_F32",
        opcode: 343,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_I32",
        opcode: 344,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_U32",
        opcode: 345,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_U8",
        opcode: 346,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_HI_U8",
        opcode: 347,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_U16",
        opcode: 348,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_U32",
        opcode: 349,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PK_U8_F32",
        opcode: 350,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FIXUP_F32",
        opcode: 351,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FIXUP_F64",
        opcode: 352,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_F64",
        opcode: 356,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_F64",
        opcode: 357,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_F64",
        opcode: 358,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_F64",
        opcode: 359,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LDEXP_F64",
        opcode: 360,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_LO_U32",
        opcode: 361,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_U32",
        opcode: 362,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_I32",
        opcode: 364,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FMAS_F32",
        opcode: 367,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FMAS_F64",
        opcode: 368,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MSAD_U8",
        opcode: 369,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_QSAD_PK_U16_U8",
        opcode: 370,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MQSAD_PK_U16_U8",
        opcode: 371,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_TRIG_PREOP_F64",
        opcode: 372,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MQSAD_U32_U8",
        opcode: 373,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_XOR3_B32",
        opcode: 376,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_NOP",
        opcode: 384,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOV_B32",
        opcode: 385,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_READFIRSTLANE_B32",
        opcode: 386,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_I32_F64",
        opcode: 387,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F64_I32",
        opcode: 388,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_I32",
        opcode: 389,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_U32",
        opcode: 390,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_U32_F32",
        opcode: 391,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_I32_F32",
        opcode: 392,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F16_F32",
        opcode: 394,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_F16",
        opcode: 395,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_RPI_I32_F32",
        opcode: 396,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_FLR_I32_F32",
        opcode: 397,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_OFF_F32_I4",
        opcode: 398,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_F64",
        opcode: 399,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F64_F32",
        opcode: 400,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_UBYTE0",
        opcode: 401,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_UBYTE1",
        opcode: 402,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_UBYTE2",
        opcode: 403,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F32_UBYTE3",
        opcode: 404,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_U32_F64",
        opcode: 405,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F64_U32",
        opcode: 406,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_TRUNC_F64",
        opcode: 407,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CEIL_F64",
        opcode: 408,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RNDNE_F64",
        opcode: 409,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FLOOR_F64",
        opcode: 410,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_PIPEFLUSH",
        opcode: 411,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FRACT_F32",
        opcode: 416,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_TRUNC_F32",
        opcode: 417,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CEIL_F32",
        opcode: 418,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RNDNE_F32",
        opcode: 419,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FLOOR_F32",
        opcode: 420,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_EXP_F32",
        opcode: 421,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LOG_F32",
        opcode: 423,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RCP_F32",
        opcode: 426,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RCP_IFLAG_F32",
        opcode: 427,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RSQ_F32",
        opcode: 430,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RCP_F64",
        opcode: 431,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RSQ_F64",
        opcode: 433,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SQRT_F32",
        opcode: 435,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SQRT_F64",
        opcode: 436,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SIN_F32",
        opcode: 437,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_COS_F32",
        opcode: 438,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_NOT_B32",
        opcode: 439,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_BFREV_B32",
        opcode: 440,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FFBH_U32",
        opcode: 441,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FFBL_B32",
        opcode: 442,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FFBH_I32",
        opcode: 443,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FREXP_EXP_I32_F64",
        opcode: 444,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FREXP_MANT_F64",
        opcode: 445,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FRACT_F64",
        opcode: 446,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FREXP_EXP_I32_F32",
        opcode: 447,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FREXP_MANT_F32",
        opcode: 448,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CLREXCP",
        opcode: 449,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELD_B32",
        opcode: 450,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELS_B32",
        opcode: 451,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELSD_B32",
        opcode: 452,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELSD_2_B32",
        opcode: 456,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F16_U16",
        opcode: 464,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_F16_I16",
        opcode: 465,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_U16_F16",
        opcode: 466,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_I16_F16",
        opcode: 467,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RCP_F16",
        opcode: 468,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SQRT_F16",
        opcode: 469,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RSQ_F16",
        opcode: 470,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LOG_F16",
        opcode: 471,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_EXP_F16",
        opcode: 472,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FREXP_MANT_F16",
        opcode: 473,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FREXP_EXP_I16_F16",
        opcode: 474,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FLOOR_F16",
        opcode: 475,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CEIL_F16",
        opcode: 476,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_TRUNC_F16",
        opcode: 477,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_RNDNE_F16",
        opcode: 478,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FRACT_F16",
        opcode: 479,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SIN_F16",
        opcode: 480,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_COS_F16",
        opcode: 481,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAT_PK_U8_I16",
        opcode: 482,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_NORM_I16_F16",
        opcode: 483,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_NORM_U16_F16",
        opcode: 484,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P1_F32",
        opcode: 512,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P2_F32",
        opcode: 513,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_MOV_F32",
        opcode: 514,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHLREV_B64",
        opcode: 767,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHRREV_B64",
        opcode: 768,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ASHRREV_I64",
        opcode: 769,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_U16",
        opcode: 771,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_U16",
        opcode: 772,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_LO_U16",
        opcode: 773,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHRREV_B16",
        opcode: 775,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ASHRREV_I16",
        opcode: 776,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_U16",
        opcode: 777,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_I16",
        opcode: 778,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_U16",
        opcode: 779,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_I16",
        opcode: 780,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_I16",
        opcode: 781,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_I16",
        opcode: 782,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_PACK_B32_F16",
        opcode: 785,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PKNORM_I16_F16",
        opcode: 786,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PKNORM_U16_F16",
        opcode: 787,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHLREV_B16",
        opcode: 788,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_U16",
        opcode: 832,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P1LL_F16",
        opcode: 834,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P1LV_F16",
        opcode: 835,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_PERM_B32",
        opcode: 836,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_XAD_U32",
        opcode: 837,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHL_ADD_U32",
        opcode: 838,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_LSHL_U32",
        opcode: 839,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_F16",
        opcode: 843,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_F16",
        opcode: 849,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_I16",
        opcode: 850,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_U16",
        opcode: 851,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_F16",
        opcode: 852,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_I16",
        opcode: 853,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_U16",
        opcode: 854,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_F16",
        opcode: 855,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_I16",
        opcode: 856,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_U16",
        opcode: 857,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P2_F16",
        opcode: 858,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_I16",
        opcode: 862,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FIXUP_F16",
        opcode: 863,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_READLANE_B32",
        opcode: 864,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_WRITELANE_B32",
        opcode: 865,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LDEXP_F32",
        opcode: 866,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_BFM_B32",
        opcode: 867,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_BCNT_U32_B32",
        opcode: 868,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MBCNT_LO_U32_B32",
        opcode: 869,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MBCNT_HI_U32_B32",
        opcode: 870,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PKNORM_I16_F32",
        opcode: 872,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PKNORM_U16_F32",
        opcode: 873,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PK_U16_U32",
        opcode: 874,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CVT_PK_I16_I32",
        opcode: 875,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD3_U32",
        opcode: 877,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHL_OR_B32",
        opcode: 879,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_AND_OR_B32",
        opcode: 881,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_OR3_B32",
        opcode: 882,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_U32_U16",
        opcode: 883,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_I32_I16",
        opcode: 885,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_I32",
        opcode: 886,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_PERMLANE16_B32",
        opcode: 887,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_PERMLANEX16_B32",
        opcode: 888,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_I32",
        opcode: 895,
        is_branch: false,
        is_terminator: false,
    },
];

/// Look up an instruction by opcode.
#[must_use]
pub fn lookup(opcode: u16) -> Option<&'static InstrEntry> {
    TABLE.iter().find(|e| e.opcode == opcode)
}
