// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::super::isa_types::InstrEntry;

pub const TABLE: &[InstrEntry] = &[
    InstrEntry {
        name: "V_CMP_F_I32",
        opcode: 128,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_I32",
        opcode: 129,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_I32",
        opcode: 130,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_I32",
        opcode: 131,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_I32",
        opcode: 132,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_I32",
        opcode: 133,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_I32",
        opcode: 134,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_I32",
        opcode: 135,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_I16",
        opcode: 137,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_I16",
        opcode: 138,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_I16",
        opcode: 139,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_I16",
        opcode: 140,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_I16",
        opcode: 141,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_I16",
        opcode: 142,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_I32",
        opcode: 144,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_I32",
        opcode: 145,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_I32",
        opcode: 146,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_I32",
        opcode: 147,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_I32",
        opcode: 148,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_I32",
        opcode: 149,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_I32",
        opcode: 150,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_I32",
        opcode: 151,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_I16",
        opcode: 153,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_I16",
        opcode: 154,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_I16",
        opcode: 155,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_I16",
        opcode: 156,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_I16",
        opcode: 157,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_I16",
        opcode: 158,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_I64",
        opcode: 160,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_I64",
        opcode: 161,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_I64",
        opcode: 162,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_I64",
        opcode: 163,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_I64",
        opcode: 164,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_I64",
        opcode: 165,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_I64",
        opcode: 166,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_I64",
        opcode: 167,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_U16",
        opcode: 169,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_U16",
        opcode: 170,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_U16",
        opcode: 171,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_U16",
        opcode: 172,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_U16",
        opcode: 173,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_U16",
        opcode: 174,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_I64",
        opcode: 176,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_I64",
        opcode: 177,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_I64",
        opcode: 178,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_I64",
        opcode: 179,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_I64",
        opcode: 180,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_I64",
        opcode: 181,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_I64",
        opcode: 182,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_I64",
        opcode: 183,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_U16",
        opcode: 185,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_U16",
        opcode: 186,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_U16",
        opcode: 187,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_U16",
        opcode: 188,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_U16",
        opcode: 189,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_U16",
        opcode: 190,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_U32",
        opcode: 192,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_U32",
        opcode: 193,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_U32",
        opcode: 194,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_U32",
        opcode: 195,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_U32",
        opcode: 196,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_U32",
        opcode: 197,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_U32",
        opcode: 198,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_U32",
        opcode: 199,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_U32",
        opcode: 208,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_U32",
        opcode: 209,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_U32",
        opcode: 210,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_U32",
        opcode: 211,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_U32",
        opcode: 212,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_U32",
        opcode: 213,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_U32",
        opcode: 214,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_U32",
        opcode: 215,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_U64",
        opcode: 224,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_U64",
        opcode: 225,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_U64",
        opcode: 226,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_U64",
        opcode: 227,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_U64",
        opcode: 228,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NE_U64",
        opcode: 229,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_U64",
        opcode: 230,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_T_U64",
        opcode: 231,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_U64",
        opcode: 240,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_U64",
        opcode: 241,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_U64",
        opcode: 242,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_U64",
        opcode: 243,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_U64",
        opcode: 244,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NE_U64",
        opcode: 245,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_U64",
        opcode: 246,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_T_U64",
        opcode: 247,
        is_branch: false,
        is_terminator: false,
    },
];

#[must_use]
pub fn lookup(opcode: u16) -> Option<&'static InstrEntry> {
    TABLE.iter().find(|e| e.opcode == opcode)
}
