// SPDX-License-Identifier: AGPL-3.0-only
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::super::isa_types::InstrEntry;

pub const TABLE: &[InstrEntry] = &[
    InstrEntry {
        name: "V_CNDMASK_B32",
        opcode: 257,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_F32",
        opcode: 259,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_F32",
        opcode: 260,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUBREV_F32",
        opcode: 261,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMAC_LEGACY_F32",
        opcode: 262,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_LEGACY_F32",
        opcode: 263,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_F32",
        opcode: 264,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_I32_I24",
        opcode: 265,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_I32_I24",
        opcode: 266,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_U32_U24",
        opcode: 267,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_U32_U24",
        opcode: 268,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_F32",
        opcode: 271,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_F32",
        opcode: 272,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_I32",
        opcode: 273,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_I32",
        opcode: 274,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_U32",
        opcode: 275,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_U32",
        opcode: 276,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_U32",
        opcode: 293,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_U32",
        opcode: 294,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUBREV_NC_U32",
        opcode: 295,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMAC_F32",
        opcode: 299,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_F16",
        opcode: 306,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_F16",
        opcode: 307,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUBREV_F16",
        opcode: 308,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_F16",
        opcode: 309,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMAC_F16",
        opcode: 310,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_F16",
        opcode: 313,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_F16",
        opcode: 314,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_LEGACY_F32",
        opcode: 320,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_I32_I24",
        opcode: 322,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_U32_U24",
        opcode: 323,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBEID_F32",
        opcode: 324,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBESC_F32",
        opcode: 325,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBETC_F32",
        opcode: 326,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CUBEMA_F32",
        opcode: 327,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_F32",
        opcode: 331,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_F64",
        opcode: 332,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LERP_U8",
        opcode: 333,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MULLIT_F32",
        opcode: 336,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_F32",
        opcode: 337,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_I32",
        opcode: 338,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_U32",
        opcode: 339,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_F32",
        opcode: 340,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_I32",
        opcode: 341,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_U32",
        opcode: 342,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_F32",
        opcode: 343,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_I32",
        opcode: 344,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_U32",
        opcode: 345,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_U8",
        opcode: 346,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_HI_U8",
        opcode: 347,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_U16",
        opcode: 348,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAD_U32",
        opcode: 349,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FIXUP_F32",
        opcode: 351,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FIXUP_F64",
        opcode: 352,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_F64",
        opcode: 356,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_F64",
        opcode: 357,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_F64",
        opcode: 358,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_F64",
        opcode: 359,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_LO_U32",
        opcode: 361,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_U32",
        opcode: 362,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_HI_I32",
        opcode: 364,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FMAS_F32",
        opcode: 367,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FMAS_F64",
        opcode: 368,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MSAD_U8",
        opcode: 369,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_QSAD_PK_U16_U8",
        opcode: 370,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MQSAD_PK_U16_U8",
        opcode: 371,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MQSAD_U32_U8",
        opcode: 373,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_NOP",
        opcode: 384,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOV_B32",
        opcode: 385,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_READFIRSTLANE_B32",
        opcode: 386,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_PIPEFLUSH",
        opcode: 411,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CLREXCP",
        opcode: 449,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELD_B32",
        opcode: 450,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELS_B32",
        opcode: 451,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELSD_B32",
        opcode: 452,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MOVRELSD_2_B32",
        opcode: 456,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SAT_PK_U8_I16",
        opcode: 482,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P1_F32",
        opcode: 512,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P2_F32",
        opcode: 513,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_MOV_F32",
        opcode: 514,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_U16",
        opcode: 771,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_U16",
        opcode: 772,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MUL_LO_U16",
        opcode: 773,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_U16",
        opcode: 777,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX_I16",
        opcode: 778,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_U16",
        opcode: 779,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN_I16",
        opcode: 780,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_I16",
        opcode: 781,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_I16",
        opcode: 782,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_PACK_B32_F16",
        opcode: 785,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_U16",
        opcode: 832,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P1LL_F16",
        opcode: 834,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P1LV_F16",
        opcode: 835,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_XAD_U32",
        opcode: 837,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_LSHL_ADD_U32",
        opcode: 838,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_LSHL_U32",
        opcode: 839,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_FMA_F16",
        opcode: 843,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_F16",
        opcode: 849,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_I16",
        opcode: 850,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MIN3_U16",
        opcode: 851,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_F16",
        opcode: 852,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_I16",
        opcode: 853,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAX3_U16",
        opcode: 854,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_F16",
        opcode: 855,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_I16",
        opcode: 856,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MED3_U16",
        opcode: 857,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_INTERP_P2_F16",
        opcode: 858,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_I16",
        opcode: 862,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_DIV_FIXUP_F16",
        opcode: 863,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_READLANE_B32",
        opcode: 864,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_WRITELANE_B32",
        opcode: 865,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD3_U32",
        opcode: 877,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_U32_U16",
        opcode: 883,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_MAD_I32_I16",
        opcode: 885,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_SUB_NC_I32",
        opcode: 886,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_ADD_NC_I32",
        opcode: 895,
        is_branch: false,
        is_terminator: false,
    },
];

#[must_use]
pub fn lookup(opcode: u16) -> Option<&'static InstrEntry> {
    TABLE.iter().find(|e| e.opcode == opcode)
}
