// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 ecoPrimals
//! AUTO-GENERATED from AMD RDNA2 ISA XML specification.
//!
//! Source: specs/amd/amdgpu_isa_rdna2.xml (MIT license, AMD GPUOpen)
//! Generator: tools/amd-isa-gen (pure Rust, sovereign toolchain)
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!   cargo run -p amd-isa-gen

use super::super::isa_types::InstrEntry;

pub const TABLE: &[InstrEntry] = &[
    InstrEntry {
        name: "V_CMP_F_F32",
        opcode: 0,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_F32",
        opcode: 1,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_F32",
        opcode: 2,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_F32",
        opcode: 3,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_F32",
        opcode: 4,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LG_F32",
        opcode: 5,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_F32",
        opcode: 6,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_O_F32",
        opcode: 7,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_U_F32",
        opcode: 8,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGE_F32",
        opcode: 9,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLG_F32",
        opcode: 10,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGT_F32",
        opcode: 11,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLE_F32",
        opcode: 12,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NEQ_F32",
        opcode: 13,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLT_F32",
        opcode: 14,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_TRU_F32",
        opcode: 15,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_F32",
        opcode: 16,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_F32",
        opcode: 17,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_F32",
        opcode: 18,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_F32",
        opcode: 19,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_F32",
        opcode: 20,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LG_F32",
        opcode: 21,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_F32",
        opcode: 22,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_O_F32",
        opcode: 23,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_U_F32",
        opcode: 24,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGE_F32",
        opcode: 25,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLG_F32",
        opcode: 26,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGT_F32",
        opcode: 27,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLE_F32",
        opcode: 28,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NEQ_F32",
        opcode: 29,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLT_F32",
        opcode: 30,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_TRU_F32",
        opcode: 31,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_F64",
        opcode: 32,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_F64",
        opcode: 33,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_F64",
        opcode: 34,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_F64",
        opcode: 35,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_F64",
        opcode: 36,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LG_F64",
        opcode: 37,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_F64",
        opcode: 38,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_O_F64",
        opcode: 39,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_U_F64",
        opcode: 40,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGE_F64",
        opcode: 41,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLG_F64",
        opcode: 42,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGT_F64",
        opcode: 43,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLE_F64",
        opcode: 44,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NEQ_F64",
        opcode: 45,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLT_F64",
        opcode: 46,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_TRU_F64",
        opcode: 47,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_F64",
        opcode: 48,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_F64",
        opcode: 49,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_F64",
        opcode: 50,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_F64",
        opcode: 51,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_F64",
        opcode: 52,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LG_F64",
        opcode: 53,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_F64",
        opcode: 54,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_O_F64",
        opcode: 55,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_U_F64",
        opcode: 56,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGE_F64",
        opcode: 57,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLG_F64",
        opcode: 58,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGT_F64",
        opcode: 59,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLE_F64",
        opcode: 60,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NEQ_F64",
        opcode: 61,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLT_F64",
        opcode: 62,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_TRU_F64",
        opcode: 63,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_CLASS_F32",
        opcode: 136,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_CLASS_F16",
        opcode: 143,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_CLASS_F32",
        opcode: 152,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_CLASS_F16",
        opcode: 159,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_CLASS_F64",
        opcode: 168,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_CLASS_F64",
        opcode: 184,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_F_F16",
        opcode: 200,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LT_F16",
        opcode: 201,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_EQ_F16",
        opcode: 202,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LE_F16",
        opcode: 203,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GT_F16",
        opcode: 204,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_LG_F16",
        opcode: 205,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_GE_F16",
        opcode: 206,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_O_F16",
        opcode: 207,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_F_F16",
        opcode: 216,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LT_F16",
        opcode: 217,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_EQ_F16",
        opcode: 218,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LE_F16",
        opcode: 219,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GT_F16",
        opcode: 220,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_LG_F16",
        opcode: 221,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_GE_F16",
        opcode: 222,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_O_F16",
        opcode: 223,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_U_F16",
        opcode: 232,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGE_F16",
        opcode: 233,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLG_F16",
        opcode: 234,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NGT_F16",
        opcode: 235,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLE_F16",
        opcode: 236,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NEQ_F16",
        opcode: 237,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_NLT_F16",
        opcode: 238,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMP_TRU_F16",
        opcode: 239,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_U_F16",
        opcode: 248,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGE_F16",
        opcode: 249,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLG_F16",
        opcode: 250,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NGT_F16",
        opcode: 251,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLE_F16",
        opcode: 252,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NEQ_F16",
        opcode: 253,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_NLT_F16",
        opcode: 254,
        is_branch: false,
        is_terminator: false,
    },
    InstrEntry {
        name: "V_CMPX_TRU_F16",
        opcode: 255,
        is_branch: false,
        is_terminator: false,
    },
];

#[must_use]
pub fn lookup(opcode: u16) -> Option<&'static InstrEntry> {
    TABLE.iter().find(|e| e.opcode == opcode)
}
